### ISSUE TITLE
Registering actions after resource routes means actions without a URL prefix do not match

### ISSUE THREAD

**Issue by lindyhopchris** [laravel-json-api/laravel#100]
Raised via Slack. Given this example:

```php
$server->resource('users', UserController::class)
            ->actions('actions', function ($actions) {
                $actions->get('me');
            })
            ->except('store');
```

And a ID pattern of `\d`, we expect these routes to work:

- `GET /api/v1/users/1`
- `GET /api/v1/users/me`

However, the `me` route gets a `404 Not Found`. This is because the resource `show` action is registered *before* the actions, so matches first.

**Comment by osmnerdm** [comment]
I just saw your post on slack. The given example works. There is 'actions' prefix on action. 
```
$server->resource('users', UserController::class)
            ->actions(function ($actions) {
                $actions->get('me');
            });
```
This example wont work. Because as you said actions are registered before resource `show` action. So custom actions must be registered after defaults.

**Comment by lindyhopchris** [comment]
@osmnerdm it does actually work - as long as `me` does not match your ID pattern for the resource. Can you confirm what ID pattern you are using?

**Comment by lindyhopchris** [comment]
Note as to what is going on in here. I added this routing in the dummy app:

```php
$server->resource('users')->only('show')->actions(function ($actions) {
    $actions->get('me');
});
```

This doesn't work because the `users` resource is using hash-ids, so the ID pattern is `[a-zA-Z0-9]+`. That matches for `me`, so `404 Not Found` is the correct response because it's attempting to find a `users` resource with an ID of `me`.

Changing to this:

```php
$server->resource('users')->only('show')->actions(function ($actions) {
    $actions->get('-me', 'me');
});
```

works because now the action URL `-me` does not match the ID pattern, so the action route correctly matches.

It is logical for the package to not support custom actions that match the ID pattern - because under no circumstances should custom action URLs collide with resource IDs, as there's no way to distinguish the two.

So I intend to close this issue - maybe just need to add something to the docs.

**Comment by osmnerdm** [comment]
> @osmnerdm it does actually work - as long as `me` does not match your ID pattern for the resource. Can you confirm what ID pattern you are using?

That resource uses hash-ids.

**Comment by lindyhopchris** [comment]
Yeah, so using an action URL that matches the resource ID's pattern cannot be supported. I'll update the docs to make this clearer.

In the scenario of using hash-ids and wanting a `me` route your options are:

- use an action prefix, e.g. so it becomes `-actions/me`
- prefix me with something that doesn't match the regex e.g. `-me` (as I've done in the dummy app)
- set a minimum length for your hash-ids, then update the ID pattern so that it matches for the length, which should be more than 2 (so that `me` does not match)
