### ISSUE TITLE
Support for complex serialization

### ISSUE THREAD

**Issue by X-Coder264** [laravel-json-api/laravel#103]
Attribute hydration has methods for both simple conversion - deserializeUsing() - and complex hydration - fillUsing().
In comparison, attribute serialization only has support for simple conversion - serializeUsing().

It'd be nice to have support for complex serialization (which would receive the model that's being serialized in the closure too) while defining the fields in the schema. That way we don't need to add extra Eloquent accessors on our models or create a dedicated resource class if we have just one custom attribute field.

**Comment by lindyhopchris** [comment]
Actually I did get this in the latest release - `1.0.0-beta.5`.

Use the `extractUsing()` method, as documented here:

**Comment by X-Coder264** [comment]
Thank you.
