### ISSUE TITLE
Empty filter value cause an error (500)

### ISSUE THREAD

**Issue by bbprojectnet** [laravel-json-api/laravel#106]
Steps to reproduce:

- define any `WhereIn` filter
- try to `GET /api/resource?filter[name]=`

```
[2021-07-14 06:26:20] local.ERROR: Expecting filter value to be an array, or a string when a string delimiter is set. {"userId":10,"exception":"[object] (LogicException(code: 0): Expecting filter value to be an array, or a string when a string delimiter is set. at vendor\\laravel-json-api\\eloquent\\src\\Filters\\Concerns\\HasDelimiter.php:63)"} 
```

I know, i can prevent this by query class, but i think that basic cases should be handled out of box. Empty value should be treated as if it wasn't there at all, or at least, return a document error (400).

**Comment by lindyhopchris** [comment]
This needs to be handled by validation - all untrusted (i.e. from a client) input should *always* be validated. Also, I can't necessarily assume that an empty value is invalid. We have filters where `filter[name]=` would actually be acceptable... because just the presence of the filter key indicates the filter should be applied.

**Comment by bbprojectnet** [comment]
> We have filters where filter[name]= would actually be acceptable

Even if we assume so, it still does not work, because it returns an error 500.

**Comment by lindyhopchris** [comment]
Which filter class are you using?

**Comment by lindyhopchris** [comment]
The error is coming from the filter class, so it depends which one you are using.

**Comment by bbprojectnet** [comment]
`WhereIn::make('visitType', 'type')->delimiter(','),`

**Comment by lindyhopchris** [comment]
So the error is coming from here:
https://github.com/laravel-json-api/eloquent/blob/eae6b9e1318c8ea0459c4a40c701c48b7c87a9b6/src/Filters/Concerns/HasDelimiter.php#L53-L66

I'd accept a PR that returns an empty array from that method if the provided value is `null`.

**Comment by bbprojectnet** [comment]
Done.

https://github.com/laravel-json-api/eloquent/pull/14

**Comment by lindyhopchris** [comment]
Thanks! Merged.
