### ISSUE TITLE
How to always show relationship attributes?

### ISSUE THREAD

**Issue by heyiammushu** [laravel-json-api/laravel#109]
I am fetching data using /model/{id}/relation with included relation2, relation2 has relation3 with alwaysShowData defined in the relationships method of the relation2 resource, so I am getting id of the relation3 inside the payload of the relation2. But I am looking for a way to get the payload of relation3 including attributes of its resource, not only id, so I dont need additional request for it. Is it possible?

**Comment by ben221199** [comment]
Just do `/model/{id}?include=relation1,relation2,relation3`.

**Comment by lindyhopchris** [comment]
There are three options:

`GET /api/posts/1/comments` - returns the post's comments (shows all comment fields i.e. attributes and relationships)

`GET /api/posts/1/relationships/comments` - returns the identifiers of the post's comments (i.e. only their type/id).

`GET /api/posts/1?include=comments` - returns the post (all its attributes and relationships) and side loads the post's comments (shows all comment attributes etc) by adding them to the top-level `included` member of the JSON document.

**Comment by ben221199** [comment]
Actually there is a fourth:

`GET /api/posts/1` (without `include` param) - returns the post. To include relationships, they should be added to some array in PHP.

**Comment by lindyhopchris** [comment]
I'm a bit confused by the original question as to what is actually being asked. @heyiammushu if you're using an include path, the related resources should be in the top-level `included` member of the response JSON.

**Comment by ben221199** [comment]
I think he wants a recursive relation inclusion.
As far as I know, he is doing this:

`/model/{id}/relation` to get info about relation2.

`/{relation2-url}` to get info about relation 3.

`/{relation3-url}` to get data of the relation 3 model.

In that case, he could easily do: `/model/{id}?include=relation.relation2.relation3`

**Comment by lindyhopchris** [comment]
In which case, the include path depth would have to be set appropriate. As per these docs: https://laraveljsonapi.io/docs/1.0/schemas/eager-loading.html

**Comment by heyiammushu** [comment]
The eager-loading is my option here, thanks!
