### ISSUE TITLE
How to perform simple attribute transformations before an event?

### ISSUE THREAD

**Issue by fidelix** [laravel-json-api/laravel#125]
Previously, it was possible to use Adapter hooks:

https://laravel-json-api.readthedocs.io/en/latest/basics/adapters/#adapter-hooks

I know there are a bunch of hooks, but I couldn't find any examples for this in the documentation.

What would be the recommendation now to perform simple 1-2 line modifications on attributes?

I basically need to get the value of a field, do a single action, then modify the value of the field with a new value.
I know I can use Eloquent events for that, but is that the recommended way? Access to JSONAPI's original fields is not as easy this way.

**Comment by lindyhopchris** [comment]
How to modify attributes is described here:
https://laraveljsonapi.io/docs/1.0/schemas/attributes.html#attribute-hydration
