### ISSUE TITLE
Cannot get a simple implementation to work, I must be doing something wrong

### ISSUE THREAD

**Issue by chrispeeters** [laravel-json-api/laravel#126]
I have installed this on two different Laravel apps, one of them a fresh Laravel 8 + Sanctum install with solely this package and a simple Posts model. I have gone over the docs three times now, yet whatever I try to do, I always get 403 Forbidden as result. Calls to the same Posts model via standard Laravel returns the data and a 200 response. What am I doing wrong?

**Comment by lindyhopchris** [comment]
You most likely need a `PostPolicy`. This chapter is about Authorization:
https://laraveljsonapi.io/docs/1.0/requests/authorization.html

I'm aware I need to write a basic tutorial but haven't had time to do that yet.

**Comment by chrispeeters** [comment]
Indeed it was as simple as adding a policy and registering it as per Laravel docs. Thanks for helping me out here.
