### ISSUE TITLE
always including data for every relationship

### ISSUE THREAD

**Issue by robinstraub** [laravel-json-api/laravel#127]
Hi,

I am building an API and am used to produce resources that always have the data segment of their relationships. I used to use this on my frontend using this former package version. I came across this [section of the official documentation](https://laraveljsonapi.io/docs/1.0/resources/relationships.html#always-including-data) explaining how to provide it using the resource classes.

Is there a way to always provide the data, without having to write resource classes for every schema and specifying the alwaysIncludeData() on every relationship ?

**Comment by DenisaHalmaghi** [comment]
Hi @robinstraub . I don't think you can skip the creation of the resource/schema classes, but maybe [this section in the documentation](https://laraveljsonapi.io/docs/1.0/requests/query-parameters.html#default-include-paths) can help with the include paths.

**Comment by robinstraub** [comment]
Thanks for your reply, I ended up creating a trait for overloading the relationships() method of the JsonApiResource classes, which let me update the default content of the relationships: 

```
<?php

namespace App\JsonApi;

use Illuminate\Http\Request;
use LaravelJsonApi\Contracts\Resources\Serializer\Relation as SerializableRelation;

trait NormalizeRelationships
{
    /**
     * Get the resource's relationships.
     *
     * @param Request|null $request
     * @return iterable
     */
    public function relationships($request): iterable
    {
        foreach ($this->schema->relationships() as $relation) {
            if ($relation instanceof SerializableRelation && $relation->isNotHidden($request)) {
                yield $relation->serializedFieldName() => $this->relation($relation->serializedFieldName())->alwaysShowData()->withoutLinks();
            }
        }
    }
}
```

which let me have fairly simple JsonApiResource classes, given I don't need to customize the resource content :

```
<?php

namespace App\JsonApi\V1\Orders;

use App\JsonApi\NormalizeRelationships;
use LaravelJsonApi\Core\Resources\JsonApiResource;

class OrderResource extends JsonApiResource
{
    use NormalizeRelationships;
}
```

Aside from the hassle of creating the resource classes manually, this works fine for my use case.

**Comment by lindyhopchris** [comment]
To better support this use case, 1.1 (not yet tagged) adds the following:

The `JsonApiResource` class now has a protected `serializeRelation` method that you can overload to change the default serialization. I.e. you wouldn't now have to overload the `relationships()` method, and instead could do:

```php
protected function serializeRelation(SerializableRelation $relation): JsonApiRelation
{
    return parent::serializeRelation($relation)->alwaysShowData()->withoutLinks();
}
```

Also, if you wanted to make this change across the whole of your API (i.e. for every resource), you can now change the default class that is used for for the JSON:API resource. In your service provider:

```php
use LaravelJsonApi\Laravel\LaravelJsonApi;

public function register(): void
{
    LaravelJsonApi::defaultResource(MyResourceClass::class);
}
```

**Comment by lindyhopchris** [comment]
Closing as will be in the `1.1` release.
