### ISSUE TITLE
when middleware(auth:api) not used but token is passed, it doesn't detect the user and returns unauthenticated.

### ISSUE THREAD

**Issue by sahilgulati216** [laravel-json-api/laravel#129]
Here on line 302, it is using the `$auth ->guest()` method to determine whether or not to throw a 401 or 403.
https://github.com/laravel-json-api/laravel/blob/1a2205ee9aefd3edcce70e2ac6dc5dc112b7a0dc/src/Http/Requests/FormRequest.php#L297-L307

But this doesn't return a valid response when middleware('auth:api') is not used but token is passed. 
If we replace the code in line 302 with auth('api')->guest() it returns a valid response and things works fine.

Please check image for reference.
![image](https://user-images.githubusercontent.com/7644126/135405597-f1e5db08-085b-46a5-afd3-2caff1f9e164.png)

**Comment by lindyhopchris** [comment]
Hmmm, yeah so our implementation is using the default guard to check whether there is a signed in user. That's correct, as we can't assume it's `api`. If you'd used `auth:api` that middleware would have set the default guard to `api` and this would work correctly.

Why aren't you using the `auth:api` middleware?

**Comment by sahilgulati216** [comment]
I am not using middleware `auth:api` here because I am not forcing users to login to view content..  based on the content **settings** I am allowing/disallowing some features in frontend. 
Content from same API endpoint can be viewed by based on 3 different type of settings.
- public content (non authenticated)
- flexible content (authenticated and unrelated with creator) 
- private content (authenticated and related with creator) 

If I will use middleware, non authenticated users will not be able to access the content.

**Comment by lindyhopchris** [comment]
We have a production API with exactly the same usecase, i.e. optional authentication. You need to solve this via middleware - because you need it to apply across the whole of the API.

Our middleware looks like this. It works in the same way as Laravel's `auth` middleware, but it doesn't throw if there is no signed in user.

```php
namespace CloudCreativity\DanceCloud\Http\Middleware;

use Closure;
use Illuminate\Contracts\Auth\Factory;
use Illuminate\Http\Request;

class OptionalAuthenticate
{

    /**
     * The authentication factory instance.
     *
     * @var Factory
     */
    private Factory $auth;

    /**
     * Create a new middleware instance.
     *
     * @param  Factory  $auth
     * @return void
     */
    public function __construct(Factory $auth)
    {
        $this->auth = $auth;
    }

    /**
     * Handle an incoming request.
     *
     * @param Request $request
     * @param Closure $next
     * @param string ...$guards
     * @return mixed
     */
    public function handle($request, Closure $next, string ...$guards)
    {
        $this->authenticate($guards);

        return $next($request);
    }

    /**
     * Determine if the user is logged in to any of the given guards.
     *
     * @param array $guards
     * @return void
     */
    protected function authenticate(array $guards): void
    {
        if (empty($guards)) {
            $guards = [null];
        }

        foreach ($guards as $guard) {
            if ($this->auth->guard($guard)->check()) {
                $this->auth->shouldUse($guard);
                return;
            }
        }

        /**
         * If there is no authenticated user, set the guard
         * to the first one to ensure we do not use the default
         * guard.
         */
        if (is_string($guards[0])) {
            $this->auth->shouldUse($guards[0]);
        }
    }
}
```

**Comment by lindyhopchris** [comment]
Alternatively you can just write a middleware that does:

`$this->auth->shouldUse($guard)`

I.e. set the guard you know you want to use throughout all the routes that the middleware wraps.

**Comment by sahilgulati216** [comment]
Adding a custom middleware as you suggested and specifying the route like this helped. 
auth()->shouldUse('api');

Thanks.
