### ISSUE TITLE
Add French translation files

### ISSUE THREAD

**Issue by lindyhopchris** [laravel-json-api/laravel#13]
This PR in the old package added French translation files:
https://github.com/cloudcreativity/laravel-json-api/pull/586

We need to ensure we port these over to `laravel-json-api/validation` and `laravel-json-api/spec`.

**Comment by osteel** [comment]
Oh, wasn't aware of this repository! Is this essentially version 4 under a new vendor name, or a complete overhaul?

**Comment by lindyhopchris** [comment]
Yeah, it's a complete overhaul. It's still in alpha at the mo, but essentially new features go here. The `cloudcreativity/laravel-json-api` package will continue to be supported for bug fixes and new Laravel versions, but won't receive new features. I.e. we're supporting that package for existing projects because we know a lot of people have it in use in production (us included!).

**Comment by lindyhopchris** [comment]
@osteel there's just a few new error messages in the new package that need French translations. Not urgent but would you be able to provide translations? If you post them in this issue I'll take care of updating the files so no PR required.

This validation message:
https://github.com/laravel-json-api/validation/blob/develop/resources/lang/fr/validation.php#L84-L87

And a few JSON:API compliance messages:
https://github.com/laravel-json-api/spec/blob/develop/resources/lang/fr/spec.php#L79-L104

Thanks!

**Comment by osteel** [comment]
@lindyhopchris sure, here you go:

`validation.php`:

```php
    'client_id' => "Le format de :attribute n'est pas valide.",
```

`spec.php`:

```php
    'member_field_not_supported' => [
        'title' => 'Document JSON:API invalide',
        'detail' => "Le champ :field n'est pas un :type reconnu.",
        'code' => '',
    ],

    'field_expects_to_one' => [
        'title' => 'Document JSON:API invalide',
        'detail' => 'Le champ :field doit être une relation "to-one".',
        'code' => '',
    ],

    'field_expects_to_many' => [
        'title' => 'Document JSON:API invalide',
        'detail' => 'Le champ :field doit être une relation "to-many".',
        'code' => '',
    ],
```

I'm not 100% sure of the `member_field_not_supported` one though. Can you give me an example for `The field :field is not a supported :type.`?

Cheers

**Comment by lindyhopchris** [comment]
Ah yes it's 

"The field foo is not a supported attribute."
"The field bar is not a supported relationship."

foo/bar being the key name that has been submitted by the client.

:type is translated before it's passed into this message, so if you're application has a translation for *attribute* or *relationship*, that will be translated by this line:
https://github.com/laravel-json-api/spec/blob/develop/src/Translator.php#L141

**Comment by osteel** [comment]
@lindyhopchris I updated my previous answer accordingly. The difficulty in French is that you've got to plan for both feminine and masculine words 🙃 (e.g. "relation" is feminine, "attribut" is masculine).

Should be all good now.

**Comment by lindyhopchris** [comment]
Aha! Yeah I don't really remember any of my French - it's been a long time since I did it at school (and admittedly I wasn't particularly great at it!)

Thanks so much for your help!

**Comment by osteel** [comment]
@lindyhopchris I don't blame you! No worries, and ping me if more translations are needed
