### ISSUE TITLE
To-Many relationship Documentation error

### ISSUE THREAD

**Issue by Wiruu** [laravel-json-api/laravel#134]
hello, 

I'm new to this package and just reading the documentation for the first time.

in the request authorization to-many section there is a table with the verbs, uris and authorization method...

post -> updateModel and patch -> attachModel, yet when I do artisan r:l routes say that patch -> updateModel and post -> attachModel...

I seem to be able to attach a model via post and delete a model via delete, but when ever I do a patch request there is a 500 server error with "detail": "Unexpected relationship myRelationship on resource myResource."

**Comment by lindyhopchris** [comment]
@Wiruu see you've closed this. Are the docs wrong? In which case I need to fix.

**Comment by Wiruu** [comment]
Either I was wrong or docs got fixed already... in any case no need to fix... 
The other "issue" with the 500 error is related to https://github.com/laravel-json-api/laravel/issues/130

**Comment by lindyhopchris** [comment]
Going to re-open this to remind me to double check that the docs are correct.

**Comment by lindyhopchris** [comment]
Have fixed the docs - will deploy the new docs later today with the fix in.
