### ISSUE TITLE
Unable to convert document to an array

### ISSUE THREAD

**Issue by niskah-energies** [laravel-json-api/laravel#140]
Hi,

When I try to update an item, I have this error:

`Unable to convert document to an array.`

My request:

```
PATCH /api/v1/users/1 HTTP/1.1
{
   "data":{
      "type":"users",
      "id":"1",
      "attributes":{
         "email":"xxxxxxxx",
         "name":"xxxxxxxx",
         "token":"xxxxxxxx",
         "created_at":"2020-05-05T15:22:21.000000Z",
         "updated_at":"2021-11-26T14:45:55.000000Z",
         "deleted_at":null
      },
      "relationships":{
         
      }
   }
}
```

Any idea ??

**Comment by lindyhopchris** [comment]
Can you provide more information? If this is an exception, I need a stack trace to see where the error has originated from.

**Comment by niskah-energies** [comment]
I don't know why but it works now. (after I cleared browser cache)

**Comment by lindyhopchris** [comment]
Interesting! Well glad you manage to get it sorted.
