### ISSUE TITLE
is there any special reason for not support php 7.3?

### ISSUE THREAD

**Issue by rhayun** [laravel-json-api/laravel#143]
i am working with php 7.3 in my organization and i am not sure when we could upgrade
is there any special reason for this package to support php 7.4 and above?

**Comment by lindyhopchris** [comment]
Hi! Yes I'm using PHP 7.4 language features (e.g. property type-hinting, covariance) plus a JSON constant that was added in 7.4

I wouldn't go back and add 7.3 now because 7.3 is no longer supported:
https://www.php.net/supported-versions.php
