### ISSUE TITLE
Use Spatie/Laravel-permissions instead Laravel's policy implementation 

### ISSUE THREAD

**Issue by inkomomutane** [laravel-json-api/laravel#145]
I have project that i'm using spatie/laravel-permissions package to make authorizations, so now i building a api to comunicate with mobile device so my questions is:
Have a way to use spatie/laravel-permissions implementation instead laravel's policy for this package?

**Comment by lindyhopchris** [comment]
Hi! So this is straight-forward. Our implementation can be completely customised by writing an `Authorizer` class. That is documented here: https://laraveljsonapi.io/docs/1.0/requests/authorization.html#customising-authorization

So you should easily be able to write and authorizer that works with Spatie's package. If you need any inspiration, this is the authorizer class that works with Laravel's policies:
https://github.com/laravel-json-api/core/blob/develop/src/Core/Auth/Authorizer.php

That should give you enough to go on, so I'm going to close this issue as the question is answered.
