### ISSUE TITLE
Unable to filter resource with custom controller

### ISSUE THREAD

**Issue by michealorion** [laravel-json-api/laravel#148]
Hello, everyone.

I wanted to implement filters for a resource that has only one index route and is managed by a custom controller.

As per the documentation I have defined filters in the schema, but if I go to filter the data it always returns all the results.

Do I need to define something in the controller?

displaySchema.php
```
` public function fields(): array
    {
        return [
            ID::make(),
            Str::make('slug','name'),
            Str::make('online'),
            Str::make('name','desc'),
            Str::make('model'),
            Str::make('OS'),
            Str::make('address'),
            Str::make('timezone'),
            Str::make('display_orientation'),
            Str::make('network_type'),
            Str::make('token'),
            Str::make('serial_number'),
            Str::make('firmware_version'),
            Str::make('mac_address'),
            Number::make('resolution_width'),
            Number::make('resolution_height'),
            DateTime::make('created_time','insert_date'),
        ];
    }
    /**
     * Get the resource filters.
     *
     * @return array
     */
    public function filters(): array
    {
        return [
            WhereIdIn::make($this),
            Where::make('online')
            //online,name,slug,model,os,address,timezone,display_orientation,network_type,firmaware_version
        ];
    }
```
`
DisplayController.php

```
class DisplayController extends Controller
{

    use Actions\FetchMany;
    use Actions\FetchOne;
    use Actions\Store;
    use Actions\Update;
    use Actions\Destroy;
    use Actions\FetchRelated;
    use Actions\FetchRelationship;
    use Actions\UpdateRelationship;
    use Actions\AttachRelationship;
    use Actions\DetachRelationship;


    public function index(){
        return DataResponse::make( Display::whereIn('idsale',Sales::getSalesLoggedCustomer())->orderBy('desc')->get())->withServer('v1');
    }
```
`

**Comment by lindyhopchris** [comment]
Yeah you're getting all the `Display` models from the database when you call `get()` on the query. So you're not doing any filtering.

Looking at what you're trying to do in that method, you don't need to write the action yourself.

What are you attempting to achieve? To filter the `Display` models so that the logged in customer only gets the ones they have access to? In which case you don't need to write your own `index()` action, you need to use index filtering as documented here:
https://laraveljsonapi.io/docs/1.0/requests/authorization.html#index-filtering

**Comment by michealorion** [comment]
Thanks @lindyhopchris,

I was able to solve it thanks to your precious suggestions.
I really missed index filtering in the documentation.

**Comment by lindyhopchris** [comment]
No problem, glad you've got it sorted.
