### ISSUE TITLE
How to create related data

### ISSUE THREAD

**Issue by freimaks** [laravel-json-api/laravel#150]
Hi!

I cannot figure out how to correctly create data related to other data. The documentation provides an example with a blog post and comments. But it is not shown how to correctly create comments.

If I understand the documentation and the spec correctly, we only use the route POST ```/posts/1/relationships/comments``` to attach an existing comment to a blog post.

Apparently, to create a comment, we must use the standard route POST ```/comments```. If so, then the information passed in the request should look something like this:
```json
{
  "data": {
    "type": "comments",
    "attributes": {
      "comment": "My comment"
    },
    "relationships": {
      "post": {
        "data": {
          "type": "posts",
          "id": "1"
        }
      }
    }
  }
}
```

Next, I probably have to write my processing in the controller, etc. Am I right? Or does the related data need to be created in some other way? For example, we can simply add the post_id field to the attributes of the new comment.

**Comment by freimaks** [comment]
I found my mistake. I listed the blog as ```readOnly``` in the comment scheme.

**Comment by RobyCigar** [comment]
same problem here

**Comment by lindyhopchris** [comment]
This is all unit testing and working in production. @RobyCigar if you're having problems you'll need to provide more detail.

**Comment by RobyCigar** [comment]
sorry for my response,
heres my problem, I tried to follow this docs where the reader can create a resource with the corresponding relationships https://laraveljsonapi.io/docs/2.0/tutorial/05-creating-resources.html

I tried to follow the same step, i have the following ProductSchema.php
```
// other code
    /**
     * Get the resource fields.
     *
     * @return array
     */
    public function fields(): array
    {
        return [
            ID::make(),
            Str::make('name')->sortable(),
            Str::make('description')->sortable(),
            Number::make('stock')->sortable(),
            Number::make('price')->sortable(),
            DateTime::make('createdAt')->sortable()->readOnly(),
            DateTime::make('updatedAt')->sortable()->readOnly(),
            BelongsTo::make('product-categories', 'productCategories'),
        ];
    }
// other code
```

and ProductRequest.php
```
class ProductRequest extends ResourceRequest
{

    /**
     * Get the validation rules for the resource.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'string', Rule::unique('products', 'name')],
            'description' => ['nullable'],
            'stock' => ['required', 'integer'],
            'price' => ['required', 'integer'],
            'product-category' => JsonApiRule::toOne()
        ];
    }

}

```

heres the Product model
```
class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'description',
        'price',
        'stock',
        'product_category_id'
    ];

    public function serving($model) {
        dd($model);
    }

    public function productCategories(): BelongsTo {
        return $this->belongsTo(ProductCategory::class, 'product_category_id');
    }
}

```
and heres my table definition
```
       Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name', 50)->nullable(false);
            $table->string('description');
            $table->integer('price');
            $table->integer('stock');
            $table->foreignId('product_category_id')->on('id');
            $table->timestamps();
        });
```

I tried to fill the product resource with product-category relationships with these payload

```
{
    "data": {
        "type": "products",
        "attributes": {
            "description": "In",
            "price": 20000,
            "stock": 10,
            "name": "How"
        },
        "relationships": {
            "product-categories": {
                "data": {
                    "type": "product-categories",
                    "id": "2"
                }
            }
        }
    }
}
```
![image](https://user-images.githubusercontent.com/69680330/218231907-293197e2-f924-437c-b7c7-02f7ceb6f651.png)

but somehow the product_category_id column is not there

**Comment by lindyhopchris** [comment]
So the `serving()` thing has nothing to do with what you're trying to do, so you can disregard that.

The problem is in the `rules()` method of your validator. You've got this:

```
'product-category' => JsonApiRule::toOne()
```

but shouldn't it be this?

```
'product-categories' => JsonApiRule::toOne()
```

we only fill validated data, so if your validation is wrong the value won't be transferred over to the model.

**Comment by RobyCigar** [comment]
thank you so much, i didnt notice that the `rules()` is mapped to the schema, i thought it map to the model directly.
again thank you for the awesome library
