### ISSUE TITLE
How to include localized relations based on header accept language? 

### ISSUE THREAD

**Issue by ProteanCode** [laravel-json-api/laravel#152]
I have a table that has roles, and another table that contains its translations, so let's say a role with ID=1 has corresponding translation for N languages

Now when I query for
`/v1/roles` when passing `Accept-Language` header with `en` value, I would expect it to return only roles that has english translations

However it is not clear for me how to do that with eager loading

For now I am using this trick in Eloquent Model

```
    protected static function booted()
    {
        if(request()->hasHeader('Accept-Language')) {
            static::addGlobalScope(new LanguageScope);
        }
    }
```

But this is hacky. I want to solve it on library level

~~Also from what I see I am not able to filter the data inside the include array? I do not need translations from other languages~~
Got it here https://laraveljsonapi.io/docs/1.0/requests/authorization.html#hiding-entire-resources in that small info box

_Index filtering does not affect include paths. If you need to hide resources from appearing via an include path, you should use the hiding entire resources approach described above._

**Comment by ProteanCode** [comment]
Oh okay so my approach is okay with the small difference that I should put it in the Server class instead of a Model

**Comment by lindyhopchris** [comment]
Yep, would have definitely said this should be a global scope added via the `Server::serving()` hook. Glad you also came to the same conclusion!
