### ISSUE TITLE
Laravel 9 Support

### ISSUE THREAD

**Issue by lindyhopchris** [laravel-json-api/laravel#157]
Have reviewed the upgrade guide for Laravel 9. Most of it looks like it won't affect the Laravel JSON:API packages, so hopefully this should possibly be an easy upgrade and we may even be able to support Laravel 8 and 9 on the same version.

Upgrade guide here:
https://laravel.com/docs/master/upgrade

### Lang Files

The one thing that will is this note about publishing `lang` files, which a couple of our packages do. This might be non-breaking if we can switch to using `app()->langPath()` in the existing version:
https://laravel.com/docs/master/upgrade#the-lang-directory

### Form Request validated method

There's a change to the `validated()` method signature on form request classes. Need to double-check that doesn't affect us:

```php
public function validated($key = null, $default = null)
```

### Unvalidated Array Keys

Don't think this will affect us, but it might be a gotcha for upgrading applications. Need to double check the impact:
https://laravel.com/docs/master/upgrade#unvalidated-array-keys

**Comment by lindyhopchris** [comment]
Just a note here that we are dependent on a few third party packages also upgrading to Laravel 9. So that might slow down tagging a bit once Laravel 9 is officially released.

**Comment by lindyhopchris** [comment]
See #160 - if we remove the third-party dependency from our tests in this package, we can upgrade quicker.

**Comment by lindyhopchris** [comment]
Update on Laravel 9 - it's currently working on the untagged `2.x` branch, so I'm planning version `2.0` to work with both Laravel 8 and 9. 

However I'm keen to wait until Laravel 9 has been officially tagged as `9.0` before tagging this package, just in case they introduce anything breaking before that final tag.

Apparently Laravel 9 is scheduled for release on 8th Feb.

**Comment by X-Coder264** [comment]
Laravel 9 was just tagged :tada:

https://github.com/laravel/framework/releases/tag/v9.0.0

**Comment by lindyhopchris** [comment]
Good news! I may not have time tonight to go through and tag everything, but if I don't I should tomorrow evening. (FYI I'm on UK time.)

**Comment by lindyhopchris** [comment]
I've tagged `2.0.0`. I haven't updated the docs website yet or written an upgrade guide. But the upgrade is pretty straightforward, so the adventurous amongst you should find that you can update without an upgrade guide, particularly if you've got an ace test suite.

Hoping to update the docs website tomorrow evening (UK time).
