### ISSUE TITLE
Can't explain this issue, 500 status code with response 1

### ISSUE THREAD

**Issue by ionut-tanasa** [laravel-json-api/laravel#158]
hi there :)

i am trying to set up this package and follow the tutorial on the docs.

i am running in a strange issue when i register the route 

```
JsonApiRoute::server('v1')->prefix('v1')->resources(function ($server) {
    $server->resource('users', JsonApiController::class)->readOnly();
});
```

I followed every step in the tutorial and just did a resource (User instead of Post) to play around.

If I don't register the route i get the correct response:

```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "status": "404",
            "title": "Non trovato"
        }
    ]
}
```

If i register the route it stops working. Giving an error 500 and no response (Postman shows 1)

<img width="1304" alt="Screenshot 2022-01-18 at 22 35 15" src="https://user-images.githubusercontent.com/44393839/150022395-77ea95b0-1987-4bbd-ab07-8cc6610f8f38.png">

Running on PHP 8.1.0 and the following are my composer dependencies:

<img width="467" alt="Screenshot 2022-01-18 at 22 36 26" src="https://user-images.githubusercontent.com/44393839/150022544-4c254e3a-0e16-4460-9a5b-ddde8dd4ed35.png">

How can I even debug this? Could it be a Sail issue?

Thanks

**Comment by ionut-tanasa** [comment]
On further debugging i managed to discover the following:

```
laravel.test_1  |   syntax error, unexpected token "readonly"
laravel.test_1  | 
laravel.test_1  |   at vendor/laravel-json-api/eloquent/src/Contracts/Fillable.php:24
laravel.test_1  |      20▕ namespace LaravelJsonApi\Eloquent\Contracts;
laravel.test_1  |      21▕ 
laravel.test_1  |      22▕ use Illuminate\Database\Eloquent\Model;
laravel.test_1  |      23▕ 
laravel.test_1  |   ➜  24▕ interface Fillable extends ReadOnly
laravel.test_1  |      25▕ {
laravel.test_1  |      26▕ 
laravel.test_1  |      27▕     /**
laravel.test_1  |      28▕      * Does the model need to exist in the database before the attribute is filled?
laravel.test_1  | 
laravel.test_1  |       +4 vendor frames 
laravel.test_1  |   5   app/JsonApi/V1/Users/UserSchema.php:31
laravel.test_1  |       Composer\Autoload\ClassLoader::loadClass()
laravel.test_1  | 
laravel.test_1  |       +9 vendor frames 
laravel.test_1  |   15  routes/api.php:25
laravel.test_1  |       LaravelJsonApi\Laravel\Routing\PendingResourceRegistration::__destruct()
laravel.test_1  | 2022-01-18 21:48:26,738 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
laravel.test_1  | 2022-01-18 21:48:26,738 INFO exited: php (exit status 1; not expected)
```


```php
<?php

namespace App\JsonApi\V1\Users;

use App\Models\User;
use LaravelJsonApi\Eloquent\Contracts\Paginator;
use LaravelJsonApi\Eloquent\Fields\DateTime;
use LaravelJsonApi\Eloquent\Fields\ID;
use LaravelJsonApi\Eloquent\Filters\WhereIdIn;
use LaravelJsonApi\Eloquent\Pagination\PagePagination;
use LaravelJsonApi\Eloquent\Schema;

class UserSchema extends Schema
{

    /**
     * The model the schema corresponds to.
     *
     * @var string
     */
    public static string $model = User::class;

    /**
     * Get the resource fields.
     *
     * @return array
     */
    public function fields(): array
    {
        return [
            ID::make(),
        ];
    }

    /**
     * Get the resource filters.
     *
     * @return array
     */
    public function filters(): array
    {
        return [
            WhereIdIn::make($this),
        ];
    }

    /**
     * Get the resource paginator.
     *
     * @return Paginator|null
     */
    public function pagination(): ?Paginator
    {
        return PagePagination::make();
    }

}
```

**Comment by X-Coder264** [comment]
This package does not support PHP 8.1 yet.

https://github.com/laravel-json-api/laravel/issues/156
https://github.com/laravel-json-api/laravel/issues/138

**Comment by ionut-tanasa** [comment]
@X-Coder264 

forgot to mention i downgraded to 8.0

**Comment by X-Coder264** [comment]
I'm not sure that you did because

> syntax error, unexpected token "readonly"

this can only happen on PHP 8.1 as readonly is a reserved keyword only on PHP 8.1 due to the [read only feature](https://wiki.php.net/rfc/readonly_properties_v2)

Or maybe you now have a different error?

**Comment by ionut-tanasa** [comment]
@X-Coder264 😅 sail didn't downgrade it properly ... i'll try to fix it now. 

but if it works for everybody else that is the issue :) 

thank you very much and sorry for stealing precious time from ya

closing.
