### ISSUE TITLE
[question] Relations included by default

### ISSUE THREAD

**Issue by steveclifton** [laravel-json-api/laravel#167]
Hi - please excuse my stupid question but I need to ask

I know the docs say in several places that relationships aren't included unless requested for (as a GET param). 
But is there some way to force them to be included? 

I am looking to migrate an old application (which by default includes all entities relations) and need to maintain the same response structure. 

Appreciate I am grasping at straws here - but have to ask anyway :)

PS from using/following your tutorial - big fan of the package and your work

Cheers

**Comment by LeeJump24** [comment]
Not the maintainer of the package but I believe you are after this https://laraveljsonapi.io/docs/1.0/requests/query-parameters.html#default-include-paths.

**Comment by steveclifton** [comment]
I was sure I saw that in the docs somewhere but lost the page! 
Thanks that's just what I was looking for!

**Comment by lindyhopchris** [comment]
Thanks for answering the question quicker than me @LeeJump24 !!
