### ISSUE TITLE
Relation type is required.

### ISSUE THREAD

**Issue by mzahirr** [laravel-json-api/laravel#168]
Hi ,

 I'm getting this error if there is no type parameters in my relation object 'The member type is required.' 

Do you really need the type parameter in relationships ? Is there any way to overcome this? 

Thanks  

{
  "data": {
    "type": "tickets",
    "attributes": {
        "duedate" : "",
        "subject" : "test_subject",
        "detail" : "test_detail"
        
    },
    "relationships": {
			"slaplan": {
				"data": {
					"id": "1"
				}
			},
        
  }
}

**Comment by mzahirr** [comment]
@yzcmrfrk

**Comment by lindyhopchris** [comment]
A resource identifier is defined by the spec as the combination of the "type" and "id". So yes, the error is correct - you must provide the "type" that the "id" belongs to, otherwise there's no way to work out what the "id" is referring to.
