### ISSUE TITLE
withDefaultPerPage not working 

### ISSUE THREAD

**Issue by ppshobi** [laravel-json-api/laravel#174]
I followed the getting started guide and created posts schema and added a pagination by default 25

```
    /**
     * Get the resource paginator.
     *
     * @return Paginator|null
     */
    public function pagination(): ?Paginator
    {
        return PagePagination::make()->withDefaultPerPage(25);
    }
```

but when i visit `/posts` endpoint the response is returned without any pagination (even meta fields are not present in the response). But if I add the page size to the query `/customers?page[size]=15` . It does get paginated

**Comment by lindyhopchris** [comment]
This is working correctly. The `withDefaultPerPage()` sets the page size if the client requests pagination but does not set a page size, e.g. `/customers?page[number]=2` would return page 2 with the default per-page size (25 in your example).

To force `/posts` to return a page, even though the client hasn't requested a page, follow the "Forcing Pagination" section of the docs here:
https://laraveljsonapi.io/docs/2.0/schemas/pagination.html#forcing-pagination
