### ISSUE TITLE
Resource ID with value zero throws the exception: No JSON API resource id name set on route

### ISSUE THREAD

**Issue by dacercoolex** [laravel-json-api/laravel#178]
Trying to get a resource which ID value is zero, kinda similar to an [issue](https://github.com/cloudcreativity/laravel-json-api/issues/445) found at the former [cloudcreativity/laravel-json-api](https://github.com/cloudcreativity/laravel-json-api) throws the _LogicException_ _No JSON API resource id name set on route_. Turns out that on funtion _modelOrResourceId_ in [Route.php](https://github.com/laravel-json-api/laravel/blob/develop/src/Routing/Route.php) an assingnmet within the if stament is performed and it throws the exception because a logic value _false_ is assumed, instead of the actual 0.

Here's referenced code (at line 102):

```
    /**
     * @inheritDoc
     */
    public function modelOrResourceId()
    {
        if (!$name = $this->resourceIdName()) {
            throw new LogicException('No JSON API resource id name set on route.');
        }

        if ($modelOrResourceId = $this->route->parameter($name)) {
            return $modelOrResourceId;
        }

        throw new LogicException('No JSON API resource id set on route.');
    }
```

And this is the workaround the I've implemented in order to prevent the exception being thrown:

```
    /**
     * @inheritDoc
     */
    public function modelOrResourceId()
    {
        if (!$name = $this->resourceIdName()) {
            throw new LogicException('No JSON API resource id name set on route.');
        }

        if (!is_null($this->route->parameter($name)) && $this->route->parameter($name)!='') {
            return $this->route->parameter($name);
        }

        throw new LogicException('No JSON API resource id set on route.');
    }
```

I'm not sure if this is the best solution but, considering that it's plausible to have a resource ID = zero, it solves my issues without affecting any other values.

Hope it helps!

**Comment by lindyhopchris** [comment]
Hi! Thanks for reporting, you are right that this is a bug that needs fixing. Are you able to do a PR?

I'd prefer to assign the value to a variable then test it in the `if` statement, and use the same test as was added in the linked issue. I.e.:

```php
    public function modelOrResourceId()
    {
        if (!$name = $this->resourceIdName()) {
            throw new LogicException('No JSON API resource id name set on route.');
        }

        $modelOrResourceId = $this->route->parameter($name);

        if (!empty($modelOrResourceId) || '0' === $modelOrResourceId) {
            return $modelOrResourceId;
        }

        throw new LogicException('No JSON API resource id set on route.');
    }
```

I believe that test is ok, because the route `parameter()` method should return a string, object or null. (Object is returned if the binding has been substituted.) I don't believe it would ever return an integer.

**Comment by dacercoolex** [comment]
Hi, @lindyhopchris! 

Yes, I think your approach is more elegant, assigning the route parameter to a variable, that way there's no need to recall the getter multiple times.

I've just tested it and it worked like a charm! So, if there's no problem, I'll send a PR including your approach.

In the other hand, I'm facing another issue related with this, but this time is around resource's validation, so far I've detected that _idValidator_ class (_validate_ and _acccept_ functions) is leading to the same behavior, and so on, I'm still working because fixing it lead me to hit another obstacle. Would you suggest that I should open another issue for it or could be just chained with this one and, therefore, PR both solutions?

By the way, thanks for your quick reply!

**Comment by lindyhopchris** [comment]
No that's ok, leave it on this issue rather than opening a new issue.

**Comment by dacercoolex** [comment]
Great! Thing is that I've just realized that it's part of the spec package, so I'd have to send the PR into that one.

**Comment by lindyhopchris** [comment]
You could maybe leave that one for me to sort out.

**Comment by lindyhopchris** [comment]
@dacercoolex there were several problems in the spec package with zero ids, which I believe I've fixed. Could you give it a go?

To bring in the fix, use the following:

```bash
composer require "laravel-json-api/spec:dev-hotfix/1.1.1 as 1.1.1"
```

If it is all working for you with that fix, I can tag the packages.

**Comment by dacercoolex** [comment]
Of course @lindyhopchris! Let me test it and I'll let you know the results.

**Comment by dacercoolex** [comment]
@lindyhopchris I made some test and, after some tweaking on validation rules of my resource's request, the issue was solved. 

Thing is that, when value is zero, I had to ask if _isUpdating_ and, if it's, bypass the id's required rule. I was looking into it and seams to be at the [ResourceObject](https://github.com/laravel-json-api/core/src/Core/Document/ResourceObject.php) class.

Here's what I did to make it work:

```shell
    public function rules(): array
    {
        return ($this->isUpdating) ? [
            'name' => ['required', 'array', 'min:1'],
        ] : [
            'id' => ['required', JsonApiRule::clientId(), 'min:1', 'max:3'],
            'name' => ['required', 'array', 'min:1'],
        ];
    }
```
I know that there's a better way to accomplish this, but for testing purposes it was good enough to make it work.

**Comment by lindyhopchris** [comment]
@dacercoolex glad to hear it worked.

You shouldn't have to do that for the validation rules. If you do this:

```php
public function rules(): array
{
    return [
        'name' => ['required', 'array', 'min:1'],
        'id' => ['required', JsonApiRule::clientId(), 'min:1', 'max:3'],
    ];
}
```

Presumably it fails on update because your id of `"0"` fails the rule `"min:1"`. I'm intrigued why you're doing `min:1` when the whole point of this issue was you wanted to use zero as an id?!

**Comment by lindyhopchris** [comment]
Sorry, just twigged that you also mentioned the `ResourceObject` class... thanks for mentioning that, looking at the code I need to put a fix in there too.

**Comment by dacercoolex** [comment]
Thanks for taking the time to follow this @lindyhopchris !

You made a good point in your observation, but it would be spot on if the id were numeric, which is not my case, since values are filtered as string, so my intention with the rule is to force the string to have at least 1 character. It might be redundant being required, but I'll review it when I optimize the code during testing.

In any case, I'll test it removing the min rule in order to probe your theory.

Thanks again!
 
> Presumably it fails on update because your id of `"0"` fails the rule `"min:1"`. I'm intrigued why you're doing `min:1` when the whole point of this issue was you wanted to use zero as an id?!

**Comment by dacercoolex** [comment]
I've tested it removing the min rule and it didn't work, still fails :-(

> In any case, I'll test it removing the min rule in order to probe your theory.

**Comment by lindyhopchris** [comment]
I've just tagged the packages that have fixes in them. Please can you do the following to upgrade:

```bash
composer require laravel-json-api/laravel --no-update
composer up laravel-json-api/*
```

Then if it fail **please** provide the actual JSON:API error or exception that it is failing with? I need that to know what's failing!

**Comment by dacercoolex** [comment]
Hi @lindyhopchris 

I've just installed and tested the new release and it worked flawlessly! No issues with the zero's id, neither with the required + min:1 rules. At least on preliminary tests the issue has been solved!.

Thanks a lot again for taking the time to address this and for the great work!

**Comment by lindyhopchris** [comment]
Great, thanks for reporting glad it's now fixed!
