### ISSUE TITLE
Why JsonApiController not extend to BaseController?

### ISSUE THREAD

**Issue by joserick** [laravel-json-api/laravel#181]
Hi

I make a controller that extend to JsonApiController for create custom actions and then i specify a custom middleware() in the __construct for each of the actions but the method does not exist since the JsonApiController no extend to BaseController (Illuminate\Routing\Controller)

Is there a reason not to do this?

**Comment by lindyhopchris** [comment]
Hey! Thanks for raising. I can't remember a specific reason for not extending from the base controller, so this looks like an unintentional omission! Should be easy to fix, are you able to do a PR?
