### ISSUE TITLE
Custom actions controller methods can not use model type hints when using hash ids

### ISSUE THREAD

**Issue by Feng-Shui** [laravel-json-api/laravel#188]
When using the hash ids for a model as [per the documentation](https://laraveljsonapi.io/docs/2.0/schemas/identifier.html#hash-ids), if you create a custom action using `withId()`, you can not type hint the model correctly:

```php
class MyController extends JsonApiController
{
    /**
     * @param MyModel $model
     */
    public function customActionHandler(MyModel $model)
    {
```

This code will give you a 404:

```json
        {
            "detail": "No query results for model [App\\Models\\MyModel] x6Qe6n",
            "status": "404",
            "title": "Not Found"
        }
```

It seems to me that somewhere in `Illuminate\Routing\router::substituteImplicitBindings()` it can't resolve an instance of the model based on the hash id.

If you change the type hint to `mixed`, you don't get the 404 and you still have the correct model passed:

```php
public function customActionHandler(mixed $model)
```

I've had a look through the docs but can't see any config step that I've missed in terms of setting up hash IDs correctly, given the comments in the docs that custom actions are not likely to be needed, and hash IDs are optional, this might be an edge case when using the two.

**Comment by lindyhopchris** [comment]
This error will be originating from Laravel's substitute binding middleware. Whereas in this scenario, you need the Laravel JSON:API middleware to substitute the binding.

This section in the doc describes the problem, and the solution of removing the Laravel middleware for JSON:API routes. Does it solve your problem?
https://laraveljsonapi.io/docs/2.0/routing/#route-model-binding

**Comment by Feng-Shui** [comment]
Yep, thanks, I missed that bit!
