### ISSUE TITLE
Limit in "Eager Loading"

### ISSUE THREAD

**Issue by joserick** [laravel-json-api/laravel#193]
Hi,

I need to limit in query in relationship called through "Eager Loading".

`/api/v1/posts/1?include=comments`

```php
BelongsToMany::make('comments')->relationLoad(
    static fn($query) => $query->limit(5)
);
```

Is possible?

**Comment by BenWalters** [comment]
Hi @joserick, I think you're essentially asking for the same as has been discussed on https://github.com/laravel-json-api/laravel/issues/177 ?

**Comment by joserick** [comment]
Thank! @BenWalters, then I will be waiting for the implementation, If there is any other way to implement it without touching the model files that would be great.

**Comment by lindyhopchris** [comment]
As noted in this section of the Eloquent docs on eager loading:

> The `limit` and `take` query builder methods may not be used when constraining eager loads.

https://laravel.com/docs/9.x/eloquent-relationships#constraining-eager-loads

So this isn't something we'd be able to support.

You need to think about the design of the API. If a relationship could return far too many related resources for it to be viable for that relatinoship to be loaded without constraints, then it should be a "links only" relationship with the related data always paginated to prevent the client from getting way too many results. That's discussed in my comment here: https://github.com/laravel-json-api/laravel/issues/177#issuecomment-1086128918
