### ISSUE TITLE
Confusion over default pagination documentation

### ISSUE THREAD

**Issue by Wizofgoz** [laravel-json-api/laravel#20]
There is some conflicting information in the docs regarding pagination behavior when no page query parameters are sent by the client.

Here, it implies that requests will always be paginated by default by what is defined on the model, or by what is set as the default on the paginator:
![Screen Shot 2021-02-05 at 6 08 49 PM](https://user-images.githubusercontent.com/10892542/107105843-3cc66380-67dd-11eb-941a-cc432236a6ef.png)

But here, there is a section about forcing pagination when no query parameters are set:
![Screen Shot 2021-02-05 at 6 10 54 PM](https://user-images.githubusercontent.com/10892542/107105872-88790d00-67dd-11eb-8ed5-49af2047150d.png)

The latter is the behavior I observe as being correct but the documentation of the former makes this confusing and I'm not sure what the point of it is.

**Comment by lindyhopchris** [comment]
Ah yes I can see how that is confusing - thanks for raising.

For the page size section, it's talking about the page size it uses if the client provides page parameter but does not provide a page size for it. For example:

`GET /api/v1/posts?page[number]=1`

It will return a paginated response, with the page size specified on either the model, or the `withDefaultPerPage()` method if that has been used.

However if a client calls:

`GET /api/v1/posts`

i.e. no page parameters, then the response will not be paginated - unless you've set the `$defaultPagination` property, in which case the client will get a paginated response as per your default pagination settings.

Hope that makes sense? I'll update the docs.

**Comment by lindyhopchris** [comment]
@Wizofgoz chapter has been updated (but not deployed to the website yet). You can view it here:
https://github.com/laravel-json-api/docs/blob/develop/1.0/schemas/pagination.md#page-size

Does that make it clearer? Both sections have been updated.

**Comment by Wizofgoz** [comment]
@lindyhopchris yes, that makes a lot of sense. Thank you for the prompt response!
