### ISSUE TITLE
Cursor pagination does not support hashids

### ISSUE THREAD

**Issue by othneildrew** [laravel-json-api/laravel#201]
Having setup and followed the docs to enable [hashids](https://laraveljsonapi.io/docs/1.0/schemas/identifier.html#hash-ids), I've discovered that when using hashids with Cursor Pagination, the meta page info uses the ids from the DB column.

![5a1b926235b7a9562e1aa6a727700148](https://user-images.githubusercontent.com/24785934/175773273-f8250b8c-6fcd-4e24-8c1e-7f2d8fb88d14.png)

_Trying without validating page query. I get "the selected page.after is invalid with proper validation _
![c47f971f459a39b725c499e1561d6ece](https://user-images.githubusercontent.com/24785934/175773277-e4935c5e-dee2-498c-bdfa-34cc9826709b.png)

![f7e350b4cc839ba98b98fc2ce61f883b](https://user-images.githubusercontent.com/24785934/175773379-27d9d368-c825-4be1-af60-d1039198beb1.png)

**Comment by lindyhopchris** [comment]
Thanks for reporting this - it is indeed a bug. There's already a PR in the cursor pagination package relating to this, and my comment on it [here](https://github.com/laravel-json-api/cursor-pagination/pull/2#issuecomment-1119983145) explains that I need to amend that package so the ID field is injected into the cursor paginator.

I'll prioritise this for a fix, probably in the next week or two.

**Comment by lindyhopchris** [comment]
@othneildrew I think I've solved this but it would be good if you could give it a go.

To give it a go, run the following:

```bash
composer require "laravel-json-api/cursor-pagination:dev-feature/id-decoding"
```

To use in your schema, you would just need to do the following:

```php
public function pagination(): CursorPagination
{
    return CursorPagination::make($this->id());
}
```

**Comment by othneildrew** [comment]
@lindyhopchris My apologies that this took me soon long to review. But I'm happy to report that it works wonderfully, thanks so much for fixing this!

**Comment by lindyhopchris** [comment]
Yeah good point, I need to add some `Rule` objects that cover validating JSON:API identifiers in query parameters (JSON:API identifiers in JSON:API documents are already validated automatically).

**Comment by lindyhopchris** [comment]
Closing in favour of #237 - that documents that I need to add things to make validating resource IDs a lot easier.
