### ISSUE TITLE
Question: Create relationship items through main request

### ISSUE THREAD

**Issue by fabuhelow** [laravel-json-api/laravel#209]
Hi All,

I have a question regarding to create item and relationship items.

**The scenario:**
I have created 2 tables "country" and "city". The relationship between country and city is oneToMany 1-N.

So, is it possible to use the POST Country API to create a new cities?

**Curl Request example:**

`
curl --location --request POST 'http://laravelnew:8888/api/v1/countries' \
--header 'Accept: application/vnd.api+json' \
--header 'Content-Type: application/vnd.api+json' \
--data-raw '{
    "data": 
        {
            "type": "countries",
            "attributes": {
                "name": "Country A",
            },
            "relationships":{
                 "cities":{
                      "data":[{"name":"City A"},{"name":"City B"}]
                 }
            }
        }
 
}'
`

**Comment by lindyhopchris** [comment]
No, this is not possible with 1.0 of the spec. 1.1 of the spec will introduce an Atomic Operations extension, which will make it possible to execute multiple operations in a single request. 1.1 is due out late in September, however it will take me a bit of time to add support to this package for that extension, as I'll need to refactor a number of things to make Atomic Operations possible.

**Comment by BenWalters** [comment]
@fabuhelow whilst I don't think this is supported by the current JSON API spec, we too have come across similar issues and asking a client to make numerous requests for what seems to be a trivial task didn't sit right with us so we implemented a bit of workaround...

I'll use your scenario...

- On the Country Schema add an ArrayList named `related_cities`. Make it a hidden field (`->hidden()`)
- Implement a custom controller to override the creating logic for Country.
- Loop over the Cities and create each of them and finish by returning the created Country.

It does mean that the user doesn't get information (such as ID etc.) of the Cities... but you can workaround this by allowing them to include cities in the response.

Not suggesting this is the correct approach in line with the spec but it's an approach that I've tried and tested with this package.

**Comment by fabuhelow** [comment]
Thanks, @BenWalters @lindyhopchris . I will use the custom controller approach as of now to cover my implementation need.

**Comment by veneliniliev** [comment]
> Thanks, @BenWalters @lindyhopchris . I will use the custom controller approach as of now to cover my implementation need.

did you find a solution that works well?
