### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by casemeby** [laravel-json-api/laravel#217]
https://laraveljsonapi.io/docs/1.0/requests/authorization.html
We have error in doc looking there *(https://www.screencast.com/t/j5Gd51zT, https://www.screencast.com/t/wbXqafapNs)
need be 
`use LaravelJsonApi\Laravel\LaravelJsonApi; `

`use LaravelJsonApi\LaravelJsonApi;` - not working

Please fix it.

**Comment by lindyhopchris** [comment]
Thanks for the PR. This will be fixed when I push the next updated docs to the server.
