### ISSUE TITLE
Empty sparse fieldset parameter returns 500 error

### ISSUE THREAD

**Issue by mdpoulter** [laravel-json-api/laravel#225]
When providing an empty value to any of the `fields` query parameters, the server returns a 500 error with server error being:

> LaravelJsonApi\\Validation\\Rules\\AllowedFieldSets::notAllowed(): Argument # 2 ($fields) must be of type string, null given, called in /vendor/laravel-json-api/validation/src/Rules/AllowedFieldSets.php on line 232"

For example, if the client requests the following:

> http://localhost/api/v1/employees?fields[employees]=

It certainly makes sense for an error to be returned, but I would have expected a validation error given that this is a client issue. It also ends up in our error tracking software which isn't great.

While not an ideal solution, I wondered if adding validation for each of the `fields` parameters (current resource and all relations) would help. Unfortunately, it still returns the same 500 error for the above request. For example:

```php
'fields' => [
    'nullable',
    'array',
    JsonApiRule::fieldSets(),
],
'fields.employees' => 'filled',
```

**Comment by lindyhopchris** [comment]
Thanks for reporting. This does indeed look like a bug, so I'll get this fixed.

**Comment by lindyhopchris** [comment]
Out of interest, what do you expect the server to return when they've request no fields for the `employees` resource, as per that example?

**Comment by lindyhopchris** [comment]
Actually, have found the answer in the spec:

> An empty value indicates that no fields should be returned.

**Comment by mdpoulter** [comment]
Ah that's interesting! Thanks for investigating 😄

**Comment by lindyhopchris** [comment]
Tagged in `2.5.2` of this package. To update:

```bash
composer require laravel-json-api/laravel --no-update
composer up "laravel-json-api/*"
```

**Comment by mdpoulter** [comment]
Wow, that was fast - thank you so much!

**Comment by lindyhopchris** [comment]
Aha yeah you caught me on an evening when I was doing Laravel JSON:API admin!! 😄
