### ISSUE TITLE
Use with spatie laravel-translatable

### ISSUE THREAD

**Issue by invaders-xx** [laravel-json-api/laravel#226]
My model implements laravel-translatable and I have issue with API for Schema. I use ArrayHash for those translatable fieds but I got a exception : "LogicException: Unable to encode compound document. ". If I remove the spatie HasTranslations from Model it works. Is there a simple way to make those 2 packages working together ?

Many thanks in advance for your help.

**Comment by invaders-xx** [comment]
I solved it by creating my own API resource

**Comment by lindyhopchris** [comment]
Just FYI the exception `LogicException: Unable to encode compound document. ` has a previous exception, which is the one that caused the encoding to fail. So checking that previous exception will tell you what the problem is.

**Comment by invaders-xx** [comment]
@lindyhopchris I don't see any other exception in the error message.
