### ISSUE TITLE
Multi-Resource Models issue

### ISSUE THREAD

**Issue by invaders-xx** [laravel-json-api/laravel#227]
I followed the doc by creating a proxy, link this proxy to the policy and I have an issue with my policy's delete function parameter type : 
Argument #2 ($item) must be of type Illuminate\\Database\\Eloquent\\Model, App\\JsonApi\\Proxies\\Model given.

My delete policy declaration is as followed :

```php
public function delete(User $user, Model $item): bool
{
}
```
My proxy declaration is as followed:

```php
class Model extends Proxy
{
   
    public function __construct(OtherModel $model = null)
    {
        parent::__construct($model ?: new OtherModel());
    }
}
```

and OtherModel extends Illuminate\\Database\\Eloquent\\Model

Any thoughts ?

**Comment by lindyhopchris** [comment]
Hi! This is covered in the docs already here - https://laraveljsonapi.io/docs/3.0/digging-deeper/proxies.html#authorization

I.e. you need to tell Laravel what policy to use for the Proxy. It's described in that section in the docs. The tip under the code block is also worth reading.

I'm going to close this as I don't believe there is an issue. But if you're following that section of the docs and you think there's a bug, then reopen with more details as to why you think this is a bug.

**Comment by invaders-xx** [comment]
I did associate this Proxy model with the right one that's why I mentioned that the delete function within the policy returns that message

**Comment by lindyhopchris** [comment]
Can you share the authorizer code (for both authorisers - the proxy and the model), plus what you've put in the `AuthServiceProvider`?

**Comment by lindyhopchris** [comment]
Worth mentioning I do have this in a production app, and it's definitely working. So I suspect it's something to do with your setup (until proved otherwise!)

**Comment by invaders-xx** [comment]
My proxy is : 
```php
namespace App\JsonApi\Proxies;

use LaravelJsonApi\Eloquent\Proxy;
use Modules\Core\Entities\Company;

class Customer extends Proxy
{
  
    public function __construct(Company $customer = null)
    {
        parent::__construct($customer ?: new Company());
    }
}
```
in AuthServiceProvider :

```php
protected $policies = [
        Role::class => RolePolicy::class,
        User::class => UserPolicy::class,
        \App\JsonApi\Proxies\Supplier::class => CompanyPolicy::class,
        \App\JsonApi\Proxies\Customer::class => CompanyPolicy::class,
    ];
```

**Comment by lindyhopchris** [comment]
The issue won't be in the proxy.

What's your `CompanyPolicy` code?

**Comment by invaders-xx** [comment]
```php
public function delete(User $user, Model $item): bool
{
return $user->can('delete-company');
}
```

**Comment by lindyhopchris** [comment]
What about the import statements?

**Comment by invaders-xx** [comment]
What do you mea by import statement ?

**Comment by invaders-xx** [comment]
Hum, in the destroy function of the customer controller, should I call $customer->toBase()->delete(); instead of $customer->delete(); That's maybe the issue ?

**Comment by lindyhopchris** [comment]
Ah sorry, so seems the scope of this has changed. I was asking about import statements (`use` statements) because in your original message you were saying there was a problem with the class of the object passed to the policy.

It seems you now have a problem in the controller?

`delete()` should forward from the proxy to the model. What error are you getting now?
