### ISSUE TITLE
What are the plans to keep this in sync with Laravel releases?

### ISSUE THREAD

**Issue by genyded** [laravel-json-api/laravel#234]
If you install the latest Laravel then try to use this package, you get:

Problem 1
    - Root composer.json requires laravel-json-api/laravel ^1.1 -> satisfiable by laravel-json-api/laravel[v1.1.0].
    - laravel-json-api/laravel v1.1.0 requires php ^7.4|8.0.* -> your php version (8.2.4) does not satisfy that requirement.

We have to back rev Laravel two major version in order to use this package, Do you plan to remedy this?

**Comment by X-Coder264** [comment]
`laravel-json-api/laravel ^1.1`

You are requiring v1 of the package. v2 works with Laravel 8 and 9 and there's also v3 for Laravel 10. So you already can use this package with the latest Laravel version, you just have to require the proper package version.

**Comment by genyded** [comment]
Our bad! We did not notice the version dropdown on https://laraveljsonapi.io/docs. Thanks for the quick response!
