### ISSUE TITLE
Created resource object is empty in created hook

### ISSUE THREAD

**Issue by genyded** [laravel-json-api/laravel#243]
We create a User resource, it gets added to the DB, and all is well. However we added a controller 'created' hook and the User resource object shows up empty there. Any idea what could be causing this?

```php
namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\JsonApi\V1\Users\UserQuery;
use App\JsonApi\V1\Users\UserRequest;
use App\Models\User;
use LaravelJsonApi\Laravel\Http\Controllers\Actions;

class UserController extends Controller
{
    use Actions\FetchMany;
    use Actions\FetchOne;
    use Actions\Store;
    use Actions\Update;
    use Actions\Destroy;
    use Actions\FetchRelated;
    use Actions\FetchRelationship;
    use Actions\UpdateRelationship;
    use Actions\AttachRelationship;
    use Actions\DetachRelationship;

    public function created(User $user, UserRequest $request, UserQuery $query): void
    {
        dd($user); /*** <--- THIS IS AN EMPTY OBJECT EVEN THOUGH THE USER WAS CREATED AND ADDED TO THE DB ***/
    }
}
```

**Comment by genyded** [comment]
OK, we sort of figured this out, but still think there may be an issue here. We have a register method in an Auth Controller that uses Guzzle to create a User resource:

```php
public function register(Request $request) 
{
        // create the user via JSONAPI, this will also validate
        $resp = Http::withHeaders([
            'Content-Type' => 'application/vnd.api+json',
            'Accept' => 'application/vnd.api+json'
        ])->post('http://localhost/api/users/', $request->all());
        ...
}
```

When we create via that endpoint, the user object in the created hook of the UserController is empty. If we create a user directly via the create user endpoint, the user is populated. We would think/hope it should not matter how/where the resource is created. However it seems that the created controller hook only sees/populates the resource if it was actually 'created' vis the same controller. Any thought on how we might work around or resolve this?

**Comment by genyded** [comment]
OK, we sort of figured this out, but still think there may be an issue here. We have a register method in an Auth Controller that uses Guzzle to create a User resource:

```php
public function register(Request $request) 
{
        // create the user via JSONAPI, this will also validate
        $resp = Http::withHeaders([
            'Content-Type' => 'application/vnd.api+json',
            'Accept' => 'application/vnd.api+json'
        ])->post('http://localhost/api/users/', $request->all());
        ...
}
```

When we create via that endpoint, the user object in the created hook of the UserController is empty. If we create a user directly via the create user endpoint, the user is populated. We would think/hope it should not matter how/where the resource is created. However it seems that the created controller hook only sees/populates the resource if it was actually 'created' vis the same controller. Any thought on how we might work around or resolve this?

**Comment by genyded** [comment]
We were not passing a model, we were just hitting the create endpoint from outside the User controller (from inside an Auth Controller via Guzzle). If we hit directly it from inside the User Controller, it works. To work around it, we just modified our register route to use the method inside the User Controller instead of our Auth Controller. That works for now, but is not consistent because all our other auth related methods are in the Auth Controller.

**Comment by lindyhopchris** [comment]
Sorry, that's not what I mean. The code that executes the "created hook" passes it a model, which is then used as the model to serialize in the response:
https://github.com/laravel-json-api/laravel/blob/91d8e0cddb28efc1564c54ae6b43845dda73eb0e/src/Http/Controllers/Actions/Store.php#L61-L76

So if the model is empty in the hook, it would also be empty in the response.

**Comment by genyded** [comment]
Got it. We will try to find time for someone to dig more into it later today and follow up then. It does not 'seem' like it would be empty though because the record actually does get created.

**Comment by genyded** [comment]
OK, we figured this out and it's being caused by a work-around we had to do for https://github.com/microsoft/WSL/issues/4983#issuecomment-1541395080, which is a WSL issue, not a JSON API Issue. Closing since it's not your issue,

**Comment by lindyhopchris** [comment]
Great, thanks!
