### ISSUE TITLE
Conditional Relationship throws UnexpectedValueException('Unexpected resource relationship value.') when encoding

### ISSUE THREAD

**Issue by Wizofgoz** [laravel-json-api/laravel#25]
Example in Resource file's `relationships` method:
```php
return [
    $this->when($this->showAddress, $this->relation('address')),
];
```

Thrown in file `laravel-json-api/encoder-neomerx/src/Schema/Relationships.php` Line 103 as of `v1.0.0-alpha.3` because the `ConditionalList` iterator returns it as a `ConditionalField` instead of `JsonApiRelation`.

**Comment by lindyhopchris** [comment]
Ah yes, good point! Will get that fixed now.

**Comment by lindyhopchris** [comment]
@Wizofgoz this should be sorted now. To give it a go:

```bash
composer config minimum-stability dev
composer require laravel-json-api/laravel:^1.0.0-alpha.4 --no-update
composer up laravel-json-api/*
```

**Comment by Wizofgoz** [comment]
Looks to be fixed to me! Thank you! 👍
