### ISSUE TITLE
Hiding field using helper method like isViewingOne

### ISSUE THREAD

**Issue by od3n** [laravel-json-api/laravel#253]
Is it possible to use that?

I tried both on Schema & Resource but failed. Or I did do it the wrong way?

Currently, I use sparse fields to archive that. `fields[user] = name, email`

Any suggestion?

**Comment by lindyhopchris** [comment]
Sorry for taking a while to get back to you about this.

Sparse fieldsets is exactly how this should be done. The aim of the spec is to give the client control of what it wants in the response. The client should be explicit (via sparse fieldsets) about what fields it wants in the response, as only the client knows which fields it is actually going to make use of. The server therefore shouldn't make any decisions about what fields to show, and which ones shouldn't.

I'm going to close this issue as you're actually already doing it right by using sparse fields.
