### ISSUE TITLE
feat: ability to load relationship in resource request when validating a model (not a relationship)

### ISSUE THREAD

**Issue by paul-thebaud** [laravel-json-api/laravel#259]
This is a new feature suggestion.

## What problem is this solving

When validating a resource, it is only possible to fetch relations values from validating data when updating relationships.
The goal of this new feature is to provide a way for user to also fetch relations values from validating data when updating a model instance.

## Proposed solution

This can be done easily using current available features. Here is an example inside a ResourceRequest:

```php
$relation = new LazyRelation(
    $this->jsonApi()->server(),
    $this->schema()->relationship('author'),
    Arr::get($this->json()->all(), 'data.relationships.author'),
);

$author = $relation->get();
```

I will try to submit a PR for this feature when I got time.

**Comment by lindyhopchris** [comment]
@paul-thebaud thanks for raising this issue, sorry I've only just seen it. (Must have missed the notification.)

I'm slightly unclear on the use case here, so if you could provide an example of what you're trying to do, that would help.

At the moment I would say it's not worth you submitting a PR. I've got quite a lot of major changes made ready for the v4 release. So I think the way forward is for me to understand your use case better, then I can see whether it needs to go into the current version or v4.

**Comment by paul-thebaud** [comment]
Hi @lindyhopchris, here is a simple (and dummy) example:
Let's take an API with two resources: applications and services. An application has many services. Users can attach services to their application, but only if they have access to these services.
I want to let users update their applications using a PUT request to `/api/v1/applications/<ID>`, and change the services inside this request. Service availability is check through a Laravel policy `ServicePolicy`. This is why I need to validate the relation values (eloquent instances) and not only the given Types/IDs.
I hope this will help.
