### ISSUE TITLE
How to create resource belongsTo resource in one request?

### ISSUE THREAD

**Issue by Yeleup** [laravel-json-api/laravel#276]
example: I have a **Loan** that contains **Items**

how to create items with one request?

Now I can create an element and attach it to a Loan, but I need to implement it in one request. Can I implement this through a library?

for example: **POST api/loan/578/items**

as if explaining what I am creating for Loan

**Comment by ben221199** [comment]
In Atomic Operations, you can do it in one request. However, I don't know if the core specification supports it too. Can you give some more information about you want to do?

**Comment by Yeleup** [comment]
Loan HasMany Items
I have a POST request which add Item 
so I need to add **Item** and add it for **Loan**
