### ISSUE TITLE
Proper docs for v4.0 and Laravel 11.x

### ISSUE THREAD

**Issue by LucindaX** [laravel-json-api/laravel#283]
The tutorial docs are for v3.0 with laravel 10.x https://laraveljsonapi.io/docs/1.0/tutorial/
Can't find documentation on proper set up for a Laravel 11.x app with v4.0

**Comment by lindyhopchris** [comment]
Hi! There's no difference between versions 3 and 4, except the Laravel version.

Thanks for the reminder that I need to update the docs! I'll leave this issue open as a reminder I need to do that.

**Comment by lindyhopchris** [comment]
Have created the `4.0` doc chapters, but need to update the following before they are ready to publish:

- [ ] Exception handler as Laravel 11 has changed the usage.
- [ ] The tutorial needs tweaking to make it clear it works with Laravel 11. The exception handler might also need updating in the tutorial.

**Comment by lindyhopchris** [comment]
Docs now updated.
