### ISSUE TITLE
Error when handling validation failures

### ISSUE THREAD

**Issue by nvahalik** [laravel-json-api/laravel#287]
Appears that how `shift()` works on a collection has changed:

Laravel v10.48.12:
```
$a = collect();
$a->shift(); // null
```
Laravel v10.48.13

```
$a = collect();
$a->shift(); // Collection
```

The result of `null` when calling `->shift()` changed with this [Framework PR](https://github.com/laravel/framework/issues/51840).

This causes a problem when returning errors during validation:

https://github.com/laravel-json-api/validation/blob/2c883a5d1727cd8683deed74167956471a82272a/src/ErrorIterator.php#L115

The Elvis operator here won't fall-through to the empty array.

**Comment by asugai** [comment]
@nvahalik - looks like this is getting patched soon on the framework side to return `null` again - https://github.com/laravel/framework/pull/51841

**Comment by nvahalik** [comment]
D'oh!

I guess I misunderstood. The PR actually _fixes_ the problem. Doesn't cause it.

**Comment by lindyhopchris** [comment]
Just for safety, I've switch it to using `array_shift` instead, and I've tagged that as `v3.0.1` (as the bug was in Laravel 10).

**Comment by lindyhopchris** [comment]
Also merged the change into the Laravel 11 version, tagging `v4.1.1`.

**Comment by lindyhopchris** [comment]
FYI both those version numbers apply to the `laravel-json-api/validation` package.
