### ISSUE TITLE
QueryToMany, QueryToOne, HasMany, HasOne, BelongsTo and BelongsToMany may fail to find a relation if declared with resolveRelationUsing

### ISSUE THREAD

**Issue by danilogiacomi** [laravel-json-api/laravel#288]
If you add a relation to a model via the Model::resolveRelationUsing() method (https://laravel.com/docs/11.x/eloquent-relationships#dynamic-relationships) the getRelation() methods in QueryToMany, QueryToOne, HasMany, HasOne, BelongsTo and BelongsToMany don't recognize it as they use method_exists to check if it's available, whereas the relations created this way are only available to the instance and when checked with relationResolver

So for instance in QueryToMany.php

`
    /**
     * @return EloquentRelation
     */
    private function getRelation(): EloquentRelation
    {
        $name = $this->relation->relationName();

        assert(method_exists($this->model, $name), sprintf(
            'Expecting method %s to exist on model %s',
            $name,
            $this->model::class,
        ));
`

should be changed to something like the following:

`
    /**
     * @return EloquentRelation
     */
    private function getRelation(): EloquentRelation
    {
        $name = $this->relation->relationName();

        assert(method_exists($this->model, $name) || $this->model->relationResolver($this->model::class, $name), sprintf(
            'Expecting method %s to exist on model %s',
            $name,
            $this->model::class,
        ));
`

This way it will also work for relations declared with resolveRelationUsing

**Comment by lindyhopchris** [comment]
Hi! this is because this package pre-dates that Eloquent feature.

Any chance you could do a PR? Looks like an easy contribution?

**Comment by danilogiacomi** [comment]
> Hi! this is because this package pre-dates that Eloquent feature.
> 
> Any chance you could do a PR? Looks like an easy contribution?
> Hi! this is because this package pre-dates that Eloquent feature.
> 
> Any chance you could do a PR? Looks like an easy contribution?

Sure, but I see the repos are organized in such a way, that this is not the right one, I believe I need to operate on the laravel-json-api/eloquent one, I'll try to open it there

**Comment by danilogiacomi** [comment]
I've opened a pull request there

https://github.com/laravel-json-api/eloquent/pull/36

I believe this can be closed
