### ISSUE TITLE
Failing Installation in LA 10.x

### ISSUE THREAD

**Issue by stevebrainng** [laravel-json-api/laravel#291]
Unable to install the package in a Laravel 10 Application as we don't want to update the application to Laravel 11.

You dropped support for LA 10.x and PHP 8.1, Any specific requirement for that?

![image](https://github.com/laravel-json-api/laravel/assets/24863248/28aceb42-d5eb-4bb3-b69c-55eacffe5125)

**Comment by lindyhopchris** [comment]
Require v3 for Laravel 10:

```bash
composer require laravel-json-api/larave:^3.4
```

Laravel 11 dropped support for PHP 8.1, not us. That means we have to drop it.

We follow Laravel's support policy: https://laravel.com/docs/11.x/releases#support-policy

As Laravel 10 is only supported for bug fixes, our v3 (that uses Laravel 10) is also only supported for bug fixes currently.
