### ISSUE TITLE
Unexpected Behavior When Serializing Relationships with $this->toArray() in JsonApiResource

### ISSUE THREAD

**Issue by yazansalhi** [laravel-json-api/laravel#294]
I've encountered an unexpected behavior when using the $this->toArray() method within the attributes() method of a JsonApiResource. **Normally**, I would expect attributes and relationships to be managed separately as per JSON API specifications. However, when I use $this->toArray(), relationship data is being inlined within the attributes, which deviates from the standard JSON API response structure.

**Expected vs. Actual Behavior**
Expected Behavior: Attributes and relationships should be handled distinctly, with relationships not appearing inlined within the attributes section of the JSON API response.
Actual Behavior: When using $this->toArray() inside the attributes() method, relationship data is included inline with attributes, which is not typical for JSON API standards.

**Steps to Reproduce**

- Define a JsonApiResource with both attributes and relationships.
- Use $this->toArray() inside the attributes() method.
- Observe that the relationship data appears inline with the attributes in the JSON API response.

```
class ClientResource extends JsonApiResource
{
    public function attributes($request): iterable
    {
        return $this->toArray(); // Causes relationship data to appear inline
    }
    
    public function relationships($request): iterable
    {
        return [
            $this->relation('country')->withoutLinks()
        ];
    }
}
```

```
{
        "data": [
            {
                "type": "clients",
                "id": "10017143",
                "attributes": {
                    "customer_uid": 10017143,
                    "country": {
                          "country_uid": 23
                      },
                    }
            }
        ]
    }
```

**Impact**
This behavior could lead to confusion and potential data handling issues in client applications expecting standard JSON API formatted responses.

**Request**
I am looking for clarification if this behavior is intended or a potential oversight. Additionally, any guidance on how to prevent relationships from being inlined in attributes when using $this->toArray() would be appreciated. **OR** the opposite how to include relationship attributes inlined when using customized attributes like this example

```
class ClientResource extends JsonApiResource
{
    public function attributes($request): iterable
    {
        return [
            'clientId' => $this->customer_uid,
        ];
    }

    public function relationships($request): iterable
    {
        return [
            $this->relation('country')->withoutLinks()
        ];
    }
}
```

```
{
        "data": [
            {
                "type": "clients",
                "id": "10017143",
                "attributes": {
                    "clientId": 10017143
                    }
            }
        ]
    }
```

**Comment by lindyhopchris** [comment]
Hi. The `JsonApiResource` class does not have a `toArray()` method. When you call it, it is delegating to the model's `toArray()` method. So what you are doing is not supported.

As a side note, I'd question why you're using a resource class? Generally you shouldn't need to use it. The implementation takes care of serializing attributes and relationships automatically based on the attributes and relationships you put in your schema.
