### ISSUE TITLE
Published configuration and artisan command to create server does not play well together

### ISSUE THREAD

**Issue by jelhan** [laravel-json-api/laravel#3]
Published configuration includes a default server named `v1`: https://github.com/laravel-json-api/laravel/blob/7425ef2e0dc1ab3f81f23d6ac35455df51219c33/config/jsonapi.php#L29-L31

But publishing the configuration does not create required files for that server. `\App\JsonApi\V1\Server` does not exist.

Artisan command to create the server fails because the server is already registered:

```
$ php artisan jsonapi:server v1
Server v1 is already registered in your JSON:API configuration.
```

Must remove the server registration in `config/jsonapi.php` before creating the required files with artisan command.

`jsonapi:server` artisan command does not register the created server in `config/jsonapi.php`. Registration deleted before running the command must be added again manually after running it.

### Steps to reproduce

1. Create a new laravel project with composer installer
    ```sh
    composer create-project laravel/laravel example-app
    cd example-app
    ```
2. Install laravel-json-api/laravel (tested with `v1.0.0-alpha.1`)
    ```sh
    composer config minimum-stability alpha
    composer require laravel-json-api/laravel
    composer require --dev laravel-json-api/testing
    ```
3. Publish configuration
    ```sh
    php artisan vendor:publish --provider="LaravelJsonApi\Laravel\ServiceProvider"
    ```
4. Try to create server
    ```sh
    php artisan jsonapi:server v1
    ```

**Comment by lindyhopchris** [comment]
Thanks for reporting! Yes, need to remove or comment-out the `v1` example that's in the config file that gets published.

**Comment by jelhan** [comment]
Thanks a lot for fixing it that quickly. 🚀
