### ISSUE TITLE
Ability to have a more complex logic for determining a singular filter

### ISSUE THREAD

**Issue by X-Coder264** [laravel-json-api/laravel#36]
Currently the "singular filter" feature works on a per filter basis. In the old library the `isSearchOne` function existed on the adapter in which a more complex logic could be written, for example in the case of a composite primary key.

```php
    protected function isSearchOne(Collection $filters): bool
    {
        if ($filters->has('userId') && $filters->has('clientId')) {
            return true;
        }

        return false;
    }
```

I'm not aware if/how the same thing can be achieved with this package.

**Comment by lindyhopchris** [comment]
Yep, true this will need to be added. Thanks for reporting.

**Comment by lindyhopchris** [comment]
This is implemented as the `Schema::isSingular` method.

For example:

```php
class PostSchema extends Schema
{

    // ...

    public function isSingular(array $filters): bool
    {
        return isset($filters['userId'], $filters['clientId']);
    }

}
```
