### ISSUE TITLE
Anyone with example working code on this package, i were using the previous versiom now this gets difficult for me to go with

### ISSUE THREAD

**Issue by pro-cms** [laravel-json-api/laravel#42]
Anyone with sample code or article or tutorial on implementation of this package please share to help us lern faster about the package

**Comment by lindyhopchris** [comment]
The package is still in alpha so I haven't written a tutorial yet. There is however exceptionally extensive documentation at https://laraveljsonapi.io that I think most people are using if they're giving this new version a go.

**Comment by pro-cms** [comment]
😢you don't have any sample repo on GitHub, it will be so helpful others are learning fast through a working example like this one 
https://howtojsonapi.com/laravel.html from the previous version. But thank you for the quick reply. I Just started watching the package today, I am trying to understand the function of each directory and it is getting tough for me

**Comment by lindyhopchris** [comment]
Unfortunately it's not worth me writing a tutorial while I'm still developing the package - as I'd just end up having to modify the tutorial the whole time. I'll definitely add a tutorial once the package is settled.

In the meantime, there is actually a demo app sitting within the tests directory of this package:
https://github.com/laravel-json-api/laravel/tree/develop/tests/dummy

That would be a good place for you to start.

**Comment by shadow81627** [comment]
I have started using this package to create a things api endpoint that authenticates with Sanctum.

https://github.com/shadow81627/pocketpasta-api

**Comment by lindyhopchris** [comment]
So I have written 90% of a tutorial for the official docs. Hoping to finish it off relatively soon.

In the meantime, this blog article has been published which provides a great tutorial to the package:
https://graffino.com/web-development/how-to-use-laravel-json-api-to-create-a-json-api-compliant-backend-in-laravel

**Comment by lindyhopchris** [comment]
Tutorial now added to the official docs: https://laraveljsonapi.io/docs/1.0/tutorial/
