### ISSUE TITLE
Soft deletes are not yet supported

### ISSUE THREAD

**Issue by heyiammushu** [laravel-json-api/laravel#43]
My model implements soft deleting just as laravel documentation is describing it: uses SoftDeletes trait and has deleted_at column in migration. When I call delete method of the model outside the json api server it works fine - I still have record with deleted_at column updated. But when I am deleting record using json api server route, it's just gone and acting like force delete. Where is the point I am losing here, how to implement soft delete inside json api server?

**Comment by lindyhopchris** [comment]
Hi! So the package is tagged as alpha releases at the moment, because although it's got a lot of features it's missing a few key things. One of those is support for soft deletes. 

So the answer is it will be supported but I just haven't quite got to it yet.

**Comment by FuturFuturFutur** [comment]
> Hi! So the package is tagged as alpha releases at the moment, because although it's got a lot of features it's missing a few key things. One of those is support for soft deletes.
> 
> So the answer is it will be supported but I just haven't quite got to it yet.

Can I help you with it? I could implement this feature if you will put me on the way.

**Comment by lindyhopchris** [comment]
Hmmm, thanks for the offer but this isn't trivial to implement - so think I'll have to take this one.

**Comment by lindyhopchris** [comment]
This will be in the next release, which will either be `alpha.5` or `beta.1` - not sure yet.

If you want to give it a go now, use:

```bash
composer require laravel-json-api/laravel:dev-develop
```

The documentation (as it's not yet on the laraveljsonapi.io website) is here:
https://github.com/laravel-json-api/docs/blob/develop/1.0/schemas/soft-deleting.md
