### ISSUE TITLE
Discord Community?

### ISSUE THREAD

**Issue by glennjacobs** [laravel-json-api/laravel#46]
I'm very much aware that asking lots of questions inside of GitHub issues is likely to cause a bit of a mess for the maintainers. Would you be open to having a Discord community for general questions and support?

I say Discord because it can be used for free and retains the message history, as opposed to Slack.

**Comment by lindyhopchris** [comment]
I think I'd prefer to stick with Slack for the time being. There's not so many questions on the Slack community at the moment that message history retention is a massive issue. It's also easier for me as I've got all my other work things in Slack - I'm not a fan of having to run lots of different messenging services at once.

Thanks for the suggestion - maybe we can revisit in the future, but for the mo people should head to Slack.

**Comment by glennjacobs** [comment]
Oh, I didn't even know there was a Slack community, sorry! I looked for something on the website, maybe I'm being blind?

**Comment by glennjacobs** [comment]
Had another look, I can't find a link for it anywhere?

**Comment by lindyhopchris** [comment]
Yeah good point, I need to add it to the website. See you've managed to find the link in the meantime!

**Comment by lindyhopchris** [comment]
If anyone else is looking at this issue, here's the Slack link: https://join.slack.com/t/laraveljsonapi/shared_invite/zt-e3oi2r4y-8nkmhzpKnPQViaXrkPJHtQ

**Comment by glennjacobs** [comment]
I did, it was on the old repo :-)
