### ISSUE TITLE
Resource links should be optional

### ISSUE THREAD

**Issue by X-Coder264** [laravel-json-api/laravel#52]
I have a custom resource for monthly reports and I have only the index action for that resource. In the controller I'm just returning `new DataResponse($reports)`. 

Response example:

```json
{
    "jsonapi": {
        "version": "1.0"
    },
    "data": [
        {
            "type": "monthlyReports",
            "id": "13b1ac51-3eac-411a-b26c-d0a1ef296d9a",
            "attributes": {
                "date": "2021-02",
                "reportData": [
                    {
                        "name": "Foo",
                        "Sections started": 4,
                        "Sections completed": 1
                    },
                    {
                        "name": "Bar",
                        "Lessons started": 148,
                        "Lessons completed": 11
                    },
                    {
                        "name": "Baz",
                        "Sections started": 51,
                        "Sections completed": 23
                    }
                ]
            },
            "links": {
                "self": "http://lms.my-project.loc:8892/api/v1/monthly-reports/13b1ac51-3eac-411a-b26c-d0a1ef296d9a"
            }
        }
    ]
}
```

The problem is that I don't have the show action so there must not be any self links as they are not valid and as such they are misleading to the client (the resource ID is just `\Illuminate\Support\Str::uuid()->toString()`). There is no way to say on the `DataResponse` class that I don't want those links (as far as I can see) and if I return an empty string in the `url` method of the schema an `UnexpectedValueException` exception gets thrown in the `\LaravelJsonApi\Core\Document\LinkHref` constructor which is called in `\LaravelJsonApi\Core\Resources\JsonApiResource::selfLink()`.

As per the JSON API spec the resource links are optional:

https://jsonapi.org/format/#document-resource-object-links

> The **optional** links member within each resource object contains links related to the resource.
**If present**, this links object **MAY** contain a self link that identifies the resource represented by the resource object.
A server MUST respond to a GET request to the specified URL with a response that includes the resource as the primary data.

**Comment by lindyhopchris** [comment]
Yes good point, the self link should be optional. I'll  get this fixed for the next version (will be `1.0.0-beta.1`)

**Comment by lindyhopchris** [comment]
Note on how this is implemented. In the `Schema` class, you need to set the `$selfLink` property to `false`:

```php
class PostSchema extends Schema
{
    /**
     * Whether resources of this type have a self link.
     *
     * @var bool
     */
    protected bool $selfLink = false;
}
```

Will be in `1.0.0-beta.1` which is probably going to be tagged later today or tomorrow.

**Comment by X-Coder264** [comment]
@lindyhopchris Thank you :+1:

**Comment by lindyhopchris** [comment]
No problem! Thanks as always for your feeback!
