### ISSUE TITLE
[Question] how to add system-based fields in (store, update) without putting them into the request ?

### ISSUE THREAD

**Issue by Mina-R-Meshriky** [laravel-json-api/laravel#64]
the problem is that sometimes some fields are autogenerated by the system in creation/update. like a secret field that will be assigned a unique value for each record, but it will never be accepted by a post request.

usually in past web based projects I would create a function and put it in a trait in each model 
```php
public static function sCreate($validatedData = [], $extraData = []) {}
```
the function will first create a `new static()` of the model then I would use the `fill()` function for the validated data (to respect the fillable property), and then would also set my own extra data with the `setAttribute()` on that model
finally I save the model to the database.

How can I do something similar to that in this library ?

**Comment by lindyhopchris** [comment]
I would use model events for that, and attach the listener in the `Server:serving()` hook:
https://laraveljsonapi.io/docs/1.0/servers/events.html#api-only-events

That would be the same way you'd need to do it in Laravel Nova too.

**Comment by Mina-R-Meshriky** [comment]
yep, this works perfect
