### ISSUE TITLE
Filling fields which depend on another field depends on the order of field definition in the schema

### ISSUE THREAD

**Issue by X-Coder264** [laravel-json-api/laravel#65]
When the filling logic of a field depends on another field we can use the `fillUsing` method of an attribute to customize the filling logic. In doing so the order of the field definitions matters as the hydrator goes in order and hydrates each field.

Laravel Nova gets the entire request when it hydrates a field:

```
Text::make('Name', 'name')
    ->fillUsing(function ($request, $model, $attribute, $requestAttribute) {
        $model->{$attribute} = Str::title($request->input($attribute));
    }),

```

We could pass the entire validated request data in the `fillUsing` Closure too, so that we don't have to depend on the field definition order.

**Comment by lindyhopchris** [comment]
Just to note what I said on Slack... we don't want to pass the whole request, because we will need to decouple from requests in the near future to support #39 Atomic Operations.

So the solution is probably invoking the `fillUsing` hydrator like this:

```php
if ($this->hydrator) {
    ($this->hydrator)($model, $this->column(), $value, $validatedData);
    return;
}
```

But need to check before implementing.

**Comment by X-Coder264** [comment]
@lindyhopchris Sorry for the late response (I've had a night deploy today :smile: ). I've tried it out and it works as expected, thanks :tada:
