### ISSUE TITLE
WhereIdIn filter doesn't work

### ISSUE THREAD

**Issue by mspiderv** [laravel-json-api/laravel#68]
Version: v1.0.0-beta.1

Im getting this error "Expecting filter value to be an array, or a string when a string delimiter is set.".

URL Im hitting: http://localhost:8000/api/jsonapi/product-categories?filter[id]=3

My `filters` method in `Schema` class:

```php
public function filters(): array
    {
        return [
            WhereIdIn::make($this),
        ];
    }
```

I think the problem is here: /vendor/laravel-json-api/eloquent/src/Filters/Concerns/HasDelimiter.php on line 53:

```php
protected function toArray($value): array
    {
        if ($this->delimiter && \is_string($value)) {
            return \explode($this->delimiter, $value);
        }

        if (\is_array($value)) {
            return $value;
        }

        throw new \LogicException(
            'Expecting filter value to be an array, or a string when a string delimiter is set.'
        );
    }
```

This method throws that error, because the `$value` is simply a string.

I think this is a bug.

**Comment by lindyhopchris** [comment]
You should validate the `id` query parameter to be an array or a string, depending on which one you're using.

**Comment by lindyhopchris** [comment]
This:

`?filter[id]=3`

Is a string, so you should validate the `id` filter to be a string. If you were searching for multiple records, you would use:

`?filter[id]=3,5`

When it's a string (and assuming your delimiter is `,`).

If you intend to use an array, the format of the `id` filter should be:

`?filter[id][]=3`

And for multiple:

`?filter[id][]=3&filter[id][]=5`

**Comment by mspiderv** [comment]
Thanks for info. I thought it might be some problem with validation, but I wasn't able to find any information in docs (here: https://laraveljsonapi.io/docs/1.0/schemas/filters.html). There is not a single word about validationg query params on this particular docs subpage.

Also here https://laraveljsonapi.io/docs/1.0/schemas/filters.html#whereidin is wrong example.

This is a copy-paste from the docs:

```
GET /api/v1/posts?filter[id]=3&filter[id]=9 HTTP/1.1
Accept: application/vnd.api+json
```

As you can see, you are not passing the ID as an array.

**Comment by lindyhopchris** [comment]
Ah right yeah so that's a typo in the docs.

There's a whole chapter on query parameter validation here:
https://laraveljsonapi.io/docs/1.0/requests/query-parameters.html

But you're right that maybe the two chapters aren't cross-referenced enough.

I'll reopen this issue to remind me to fix the docs.

**Comment by lindyhopchris** [comment]
I've:

1. Fixed the typos in the docs
2. Added a section cross-referencing the filter chapter to the query parameters validation chapter
3. Added tips to the `WhereIdIn` and `WhereIdNotIn` filter sections to sate that you need to validate values as either the array or the string, depending on which you're supporting.
