### ISSUE TITLE
ArrayHash and sparse fieldsets

### ISSUE THREAD

**Issue by glennjacobs** [laravel-json-api/laravel#71]
I have a JSON database field that contains quite a lot of data. Is it possible to use the sparse fieldset functionality to return a subset of that data when mapped as an Array Hash?

**Comment by lindyhopchris** [comment]
So the JSON:API spec doesn't mention anything about using sparse fieldsets for reducing nested attribute values. The encoder we use uses the sparse fieldsets to filter the primary members of the `attributes` object, and does not support filtering of any complex array values as per your use case. That's unlikely to change as the spec doesn't define how sparse fieldsets could be used to support your use case.

My suggestion would be to use a custom (implementation-specific) query parameter to control returning a subset of that property. The JSON:API spec allows custom query parameters, you just need to ensure they are camel-cased, snake-cased or dash-cased to avoid any potential collisions with parameter names that the spec might add in the future. https://jsonapi.org/format/#query-parameters

**Comment by glennjacobs** [comment]
Thanks for the response, that all makes sense. I will give it a try when I get to that part of the project.

**Comment by lindyhopchris** [comment]
Ok great. I'll close this issue for now then.
