### ISSUE TITLE
How should I create a resource as a relationship?

### ISSUE THREAD

**Issue by lcsdms** [laravel-json-api/laravel#72]
Hi! 

I'm having the exact same questions about this [post](https://discuss.jsonapi.org/t/how-should-i-create-a-resource-as-a-relationship/299) , as pasted below:

> I’ve been googling for hours and read the specs a few times, but I haven’t found a clear answer to my problem.

> Let’s say I have users and articles. I want to create an article which will be owned by a user (that already exists). Should I call POST /articles and then call POST /users/id/relationships/articles? This seems weird to me since I know to make two calls and if my app fails between the two, there will be an article without an owner. Also, the database might not allow that anyway.
> 
> So obviously a POST call should be made on either /users/id/articles or /users/id/relationships/articles. It makes more sense to me to call POST /users/id/articles since the JSON payload will contain an entire article, not just a resource identifier and from my understanding self links only deal with resource identifiers. But I actually have no idea since the specs aren’t clear on that and there are no examples.
> 
> I’ve read about using POST /articles and having the user defined in the author relationship, but I would like to avoid that method if possible. I would prefer to be able to tell if a user is authorized or not to accomplish a certain task by only looking at the URL and not parsing the request’s body.
> 
> Thanks in advance

I think this would be the equivalent in code on laravel:

```php
$user->find($userId);
// HasMany relationship
$article = new \App\Models\Article();
$article->title = "My article";
$article->body = "lorem ipsum";
$user->articles()->save($article);
```
I have several relationships that require creating the record with the foreign key (user_id on the article table, for example).

Thanks for your help !

**Comment by lindyhopchris** [comment]
Yeah, I don't understand this - it seems like an incorrect scenario. The equivalent code in Laravel should be this:

```
$article = new \App\Models\Article();
$article->title = "My article";
$article->body = "lorem ipsum";
$article->user()->attach($user);
$article->save()
```

Because presumably the `Article` relationship has a belongs-to `User` relationship?

**Comment by lindyhopchris** [comment]
The equivalent in Laravel JSON:API if you want to attach the signed in user to the article, would be this.

The client makes this request:

```http
POST /api/v1/articles HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "articles",
    "attributes": {
      "body": "...",
      "title": "Hello World!"
    }
  }
}
```

Then to attach the current signed in user as the owner of the `Article` you would use [API-only events](https://laraveljsonapi.io/docs/1.0/servers/events.html#api-only-events) by adding a model `creating` listener in the server's `serving()` hook:

```php
namespace App\JsonApi\V1;

use App\Models\Article;
use LaravelJsonApi\Core\Server\Server as BaseServer;

class Server extends BaseServer
{

    // ...

    /**
     * Bootstrap the server when it is handling an HTTP request.
     *
     * @return void
     */
    public function serving(): void
    {
        Article::creating(static fn($article) => $article->user()->associate(request()->user()));
    }

}
```

**Comment by lcsdms** [comment]
Hey @lindyhopchris thanks for the response ! 

About the relations, it goes both ways, but I get what you said about making the binding from the article instead of the person. that makes sense, thanks !

With that in mind i've still got doubts in another similar use-case, when I won't be using the id of the current signed in user, in this example scenario, below:

- People Resource 
  - Table columns: [id, name]
- Email Resource 
  - Table columns: [id, address, person_id]

One person has many emails
One email belongs to one Person

The current logged user, is creating a people resource, and needs to register the person, and then create one or more email addresses for this person.
I'm confused on how to proceed on binding a email to a person, it looks like I should create the email resource without a person_id, and after that bind them together, is that right, or is there an easier way of binding these together ?

In the case below I would need 3 requests to do that, as I understand:

```
POST /api/v1/people HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "people",
    "attributes": {
      "name": "John"
    }
  }
}
//returns id 1
```

```
POST /api/v1/emails HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "emails",
    "attributes": {
      "address": "john@test.com"
    }
  }
}
//returns id 1
```

And then binding them together: 

```
POST api/v1/people/1/relationships/emails   HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": [
    {"type": "emails",   id: 1 }
  ]
}
```

OR

```
PATCH api/v1/people/1 HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "people",   id: 1 
   },
   "relationships": {
      "emails": {
        "data": [ "type": "emails", "id": "1" ]
      }
    }
}
```

So my question Is: 
 - Is this the only way to go (creating them separately and binding them together, resulting in 3 requests, and having the risk of emails without person_id), or is  there an easier way to create and bind related resources ?

I thought about using the API-only events in this case, and requiring the person_id on the email schema, so when posting the email, I would have to provide the person id, resulting in two requests, as below: 

```
namespace App\JsonApi\V1;

use App\Models\Email;
use LaravelJsonApi\Core\Server\Server as BaseServer;

class Server extends BaseServer
{

    // ...

    /**
     * Bootstrap the server when it is handling an HTTP request.
     *
     * @return void
     */
    public function serving(): void
    {
        Email::creating(static fn($email) => $email->person()->associate(request()->person_id()));
    }

}
```

But i'm not sure that's a good idea when managing the relationships 😛

**Comment by lindyhopchris** [comment]
No, just 2 requests.

```http
POST /api/v1/people HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "people",
    "attributes": {
      "name": "John"
    }
  }
}
```

Then

```http
POST /api/v1/emails HTTP/1.1
Accept: application/vnd.api+json
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "emails",
    "attributes": {
      "address": "john@test.com"
    },
    "relationships": {
      "person": {
        "data": {
          "type": "people",
          "id": "1"
        }
      }
    }
  }
}
```

**Comment by lindyhopchris** [comment]
If an email needs to belong to a person, it makes total sense to always require a person relationship when creating the email. Which is what the above two requests do - create the person, then create an email with a `person` relationship.

**Comment by lindyhopchris** [comment]
Closing this as the question has been answered. Reopen if you think there's anything else to ask, or ask on Slack.

**Comment by lindyhopchris** [comment]
Yeah that's a scenario you would have to design the client to handle, it's akin to a distributed transaction (aka saga) in a microservices architecture. Your client would need the error scenario.

The Atomic Operations extension will help with this scenario - I just haven't had time to fully implement that, though will finish it off at some point.
