### ISSUE TITLE
Ability to specify default includes if the client did not send any include

### ISSUE THREAD

**Issue by X-Coder264** [laravel-json-api/laravel#74]
In the previous package which used Neomerx v1 encoder we had `getIncludePaths` method in the schema (https://github.com/neomerx/json-api/blob/v1.0.9/src/Schema/SchemaProvider.php#L236)  to specify which includes would get sent back to the client if the client did not explicitly provide any includes. It'd be nice to have the same feature in this package.

**Comment by lindyhopchris** [comment]
My comment from Slack describing how this should be implemented:

Yeah this one is very simple. If you add a `$includePaths` property to the Query and QueryCollection classes, then in the `includePaths()` method, if the value from the client is `null` you return the value from the include paths property instead. The `$includePaths` property can be of mixed type: you cast it to the value object using `IncludePaths::nullable($this->includePaths)` - hopefully that'll make sense when you look at the class.
