### ISSUE TITLE
Default relation value

### ISSUE THREAD

**Issue by lo00l** [laravel-json-api/laravel#77]
Can I set the default value for my relation? Suppose I have a model `Post` and a schema for it:
```
public function fields(): iterable
{
    return [
        ID::make(),
        ...
        BelongsTo::make('author')->type('users')->readOnly(),
    ];
}
```

`readOnly()` is called because I don't want this relation to be fillable or mutable. So I need to manually fill this relation with current user during processing request `POST /api/v1/posts`. What's the best way to do this? Thank you in advance.

P.S.: Thank you for this great package! It looks really cool.

**Comment by lindyhopchris** [comment]
You should add a listener to the `Post` model's `creating` event. You can do this in the `Server::serving()` hook:
https://laraveljsonapi.io/docs/1.0/servers/events.html#api-only-events

E.g.

```php
public function serving(): void
{
    Post::creating(static fn(Post $post) => $post->user()->associate(request()->user()));
}
```
