### ISSUE TITLE
Wrong response code after new resource is created

### ISSUE THREAD

**Issue by lo00l** [laravel-json-api/laravel#79]
JSON API specification says:
> If a POST request did not include a Client-Generated ID and the requested resource has been created successfully, the server **MUST** return a 201 Created status code.

But `LaravelJsonApi\Laravel\Http\Controllers\Actions\Store::store()` method returns a response with 200 status code. 

https://github.com/laravel-json-api/laravel/blob/develop/src/Http/Controllers/Actions/Store.php#L74

So the following test fails with message `Response status code [200] does not match expected 201 status code.`:
```php
$this->jsonApi()
    ->withData([
        'type' => 'tags',
        'attributes' => [
            'title' => 'foo',
        ],
    ])
    ->post('/api/v1/tags')
    ->assertCreated();
```

Is it a bug or is 200 status code returned specially for some reasons?

Thank you in advance.

**Comment by lindyhopchris** [comment]
The `DataResponse` class will detect if the model was created during the HTTP and use a `201` response if it is.

Is there a reason why in your code the model isn't recently created?

**Comment by lindyhopchris** [comment]
FYI the `201 Created` response is tested and working in the implementation, so my initial reaction to this issue is there's something about your application that is generating the wrong response code.

The relevant section of our docs is here:
https://laraveljsonapi.io/docs/1.0/responses/#create-resource-response

**Comment by lo00l** [comment]
@lindyhopchris I forgot to mention that I have non-eloquent model and a repository for it.

Seems I had to implement `LaravelJsonApi\Contracts\Resources\Creatable` interface on my model class. 

https://github.com/laravel-json-api/core/blob/develop/src/Core/Resources/JsonApiResource.php#L202

Now it works as expected.

Thank you for the hint!

**Comment by lindyhopchris** [comment]
Great, glad you got it working!
