### ISSUE TITLE
The sort must be a string.

### ISSUE THREAD

**Issue by kraionz** [laravel-json-api/laravel#81]
When I use sort, pagination it generates an array `sort[0]=-createdAt` instead of` sort=-createdAt`

Url: 
`<url>/products?sort=-createdAt`

Links pagination:
``` json
"links": {
  "first": "<url>/products?page[number]=1&page[size]=15&sort[0]=-createdAt`",
  "last": "...",
  "next": "..."
},
```

Response : 

``` json
{
  "jsonapi": {
    "version": "1.0"
  },
  "errors": [
    {
      "detail": "The sort must be a string.",
      "source": {
        "parameter": "sort"
      },
        "status": "400",
        "title": "Invalid Query Parameter"
    }
  ]
}
```

Is there any way to correct it? Thanks in advance

**Comment by lindyhopchris** [comment]
Hi! The JSON:API spec specifies that the sort parameter is a comma separated string:
https://jsonapi.org/format/#fetching-sorting

So your request `sort[0]=-createdAt` is not compliant with the specification, which is why it is being rejected. You should use `sort=-createdAt`.

**Comment by kraionz** [comment]
Hi @lindyhopchris, thanks for your answer

I use `sort=-createdAt` in the url or by default, but the pagination returns or converts to ` sort[0]=-createdAt` on links,  which causes the error


Url: 
`<url>/products?sort=-createdAt`

Links pagination:
``` json
"links": {
  "first": "<url>/products?page[number]=1&page[size]=15&sort[0]=-createdAt`",
  "last": "...",
  "next": "..."
},
```

**Comment by lindyhopchris** [comment]
Ah sorry, I didn't understand that from your first message.

Yes that would be a bug that I need to fix!

**Comment by lindyhopchris** [comment]
Note to self: I think I've already fixed this via:
https://github.com/laravel-json-api/core/commit/d4660048bc90e6acc99b6be5a700ed6078ba67fb

However it isn't tagged yet. So should be in the next release.

**Comment by lindyhopchris** [comment]
Looks like the tests added in this commit have a `sort` query parameter, which I remember adding as I spotted there was a problem with encoding the sort parameters:
https://github.com/laravel-json-api/laravel/commit/8a4df72cf2112a06bfc09ca1df2a3c707bbc1c21

**Comment by kraionz** [comment]
Hello, I made the changes and it works perfectly, thank you very much.

We wait for the next version
