### ISSUE TITLE
Optimize repository for use with Octane

### ISSUE THREAD

**Issue by lindyhopchris** [laravel-json-api/laravel#83]
So that this package works with Laravel Octane, we need to replace any dependency injection of the container, HTTP request and config repository with *lazy loading* injections. As per these docs:
https://laravel.com/docs/8.x/octane#dependency-injection-and-octane

**Comment by lindyhopchris** [comment]
And here's the missing piece that I thought was inevitable that they'd have to introduce... new container singletons that are flushed before handling a new HTTP request or queued job, via the `scoped()` method on the container:
https://laravel.com/docs/8.x/container#binding-scoped

**Comment by isaackearl** [comment]
I'd love to see octane support with this package.  has there been any traction on this?

**Comment by lindyhopchris** [comment]
No, haven't had time yet to do this as I've had very little Open Source time recently. If someone had time to help out, this issue might be good for PRs? The first step with this issue is to identify which singletons need to be modified to either `scoped()` bindings or to follow the pattern suggested in the Octane docs linked above.

**Comment by lindyhopchris** [comment]
I've made these changes, and they will be included in the 2.0 release. I believe they should work with Octane, but as I'm not using Octane it's a bit difficult to tell for sure. If anyone is using Octane and can give the 2.0 release a go when it's tagged, that'll be appreciated!

**Comment by plunkettscott** [comment]
I can test this out on 2.0 when tagged. Just @ me.

**Comment by lindyhopchris** [comment]
@plunkettscott are you able to test out before I tag 2.0? 

You can install by setting your `minimum-stability` to `dev` in `composer.json` then running:

```bash
composer require laravel-json-api/laravel:^2.0 --no-update
composer up laravel-json-api/*
```

**Comment by plunkettscott** [comment]
Looks good. I haven't been able to inspect for memory leaks or anything yet, but if I notice them I'll report them.
