### ISSUE TITLE
Errors not returning but being logged only even in Debug true.

### ISSUE THREAD

**Issue by sahil-kindlebit** [laravel-json-api/laravel#85]
Hello,
I have this in my `Exceptions/Handler.php`
```
$this->renderable(
	\LaravelJsonApi\Exceptions\ExceptionParser::make()->acceptsJson()->renderable()
);
```
When there is some unknown error or you can say syntax error  we get this even when
`APP_DEBUG=true` & `APP_ENV=local`,
```
{
	"jsonapi": {
		"version": "1.0"
	},
	"errors": [
		{
			"status": "500",
			"title": "Internal Server Error"
		}
	]
}
```
on the other hand if I remove the code added in the` Exceptions/Handler.php` and request wants json
I get this response ->
```
{
	"message": "syntax error, unexpected '$login' (T_VARIABLE)",
	"exception": "ParseError",
	"file": "/home/vagrant/code/app/Http/Controllers/api/v1/LoginController.php",
	"line": 14,
	"trace": [
		{
			"file": "/home/vagrant/code/vendor/composer/ClassLoader.php",
			"line": 344,
			"function": "Composer\\Autoload\\includeFile"
		},
		...
	]
}
```
Currently If I remove the code from handler then I am getting error, I want my errors to be returned in response as well when using `LaravelJsonApi`.
Please help.

**Comment by lindyhopchris** [comment]
Thanks for creating an issue about this - I definitely need to add something to handle debug mode showing exception traces.

**Comment by lindyhopchris** [comment]
This will be in the next release.
