### ISSUE TITLE
Package does not yet support different media types

### ISSUE THREAD

**Issue by sahil-kindlebit** [laravel-json-api/laravel#86]
Hi, I am creating a User and I have some image fields and some text fields..
When I submit I get this error.
```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "The request entity has a media type which the server or resource does not support.",
            "status": "415",
            "title": "Unsupported Media Type"
        }
    ]
}
```
As per the compliance, I have set the headers as
```
Accept:application/vnd.api+json
Content-Type:application/vnd.api+json
```
When I was supplying the json without image field it worked fine, but after adding image field it is returning above error.
I believe in this scenario, we need to have Mixed `Content-Type` (multipart/form-data)
But I seem to find no solution when I have an image to pass in model.
I am sharing working and failed screenshot scenarios from postman.
Please guide.
![image](https://user-images.githubusercontent.com/51691497/120678877-32c81f00-c4b6-11eb-8b28-ad24f59e5510.png)
![image](https://user-images.githubusercontent.com/51691497/120678911-3bb8f080-c4b6-11eb-8df9-82945dadfd70.png)
![image](https://user-images.githubusercontent.com/51691497/120678935-44112b80-c4b6-11eb-942f-393a9b1853bd.png)

**Comment by lindyhopchris** [comment]
If you're sending an image in the payload, then the `Content-Type` will not be the JSON:API media type (because files cannot be sent with that media type). Therefore the response is correct - the media type cannot be parsed.

The old package (`cloudcreativity/laravel-json-api`) had a way of supporting different media types, but I have not added that to this package yet as it hasn't been a priority (I have limited time, so have to prioritise what I work on).

**Comment by lindyhopchris** [comment]
As a temporary work around, you should upload the image to a different endpoint that associates it with the user. That is what you would have to do anyway as the JSON:API specification does not have any provision for uploading files - as it is a JSON media type, and JSON has no file type.

**Comment by sahil-kindlebit** [comment]
Thanks, now using a separate endpoint for the uploading and then passing the name of the file to Json in next request from frontend to make this work.

**Comment by lindyhopchris** [comment]
Great, good to hear you got this working.

**Comment by xhava** [comment]
same problem here, what i am doing is implementing Min.io in the SPA and then just sent the file links to the api.

**Comment by martianatwork** [comment]
For anyone having this issue, encode the image on frontend then send the output in json, make sure that it contains the content type.

Then on Server side use creating/created event method, in this you can get the data using Laravel `request()`
Now you can access and decode the base64 data, validate it and store it. 
I'm using https://spatie.be/docs/laravel-medialibrary/v9/installation-setup for handling media.


```php
 /**
     * @param string $base64EncodedString
     * @return string
     */
    public static function getExtension(string $base64EncodedString): string {
        $extension = explode(";", explode("/", $base64EncodedString)[1])[0];
        switch ($extension) {
            case 'image/jpeg':
            case 'jpeg':
                return ".jpeg";
            case 'image/jpg':
            case 'jpg':
                return ".jpg";
            case 'image/png':
            case 'png':
                return '.png';
            case 'application/pdf':
            case 'pdf':
                return '.pdf';
            default:
                return "";
        }
    }

    /**
     * Bootstrap the server when it is handling an HTTP request.
     *
     * @return void
     */
    public function serving(): void
    {
        Model::created(static fn (Model $model) => self::handleImageUpload($model, 'awesome-image'));
    }

    /**
     * @throws JsonApiException
     */
    private static function handleImageUpload($model, string $collection, string $type = 'image') {
        $request_object = request()->json()->all();
        if(!isset($request_object['data']['attributes'][$type])) return;
        $request = $request_object['data']['attributes'][$type];
        try {
            if (!isset($request)) return;
            if(is_array($request)) {
                foreach($request as $image) {
                    try {
                        $extension = self::getExtension($image);
                    } catch (\Exception $exception) {
                        $extension = '';
                    }
                    $filename = Str::random() . $extension;
                    $model->addMediaFromBase64($image, ['image/jpeg', 'image/png','image/jpg'])->usingFileName($filename)->toMediaCollection($collection);
                }
            } else {
                try {
                    $extension = self::getExtension($request);
                } catch (\Exception $exception) {
                    $extension = '';
                }
                $filename = Str::random() . $extension;
                $model->addMediaFromBase64($request, ['image/jpeg', 'image/png','image/jpg'])->usingFileName($filename)->toMediaCollection($collection);
            }
        } catch (InvalidBase64Data | FileCannotBeAdded | FileDoesNotExist | FileIsTooBig | MimeTypeNotAllowed $exception) {
            $error = Error::fromArray([
                'title' => 'Invalid File',
                'detail' => $exception->getMessage(),
                'status' => 422,
            ]);
            throw new JsonApiException($error);
        }
    }
