### ISSUE TITLE
Validation errors are logged into file

### ISSUE THREAD

**Issue by bbprojectnet** [laravel-json-api/laravel#89]
Hi,

How to stop logging validation errors to file? I have expected api response, with for example missing value in request, but also that content in log file:

```
[2021-06-11 10:57:40] local.ERROR: JSON:API error {"exception":"[object] (LaravelJsonApi\\Core\\Exceptions\\JsonApiException(code: 0)
[...]
```

My exception handler:
```
	public function register()
	{
		$this->renderable(
			\LaravelJsonApi\Exceptions\ExceptionParser::make()->renderable()
		);
	}
```

Example response (which causes log into file):
```
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "The password field is required.",
            "source": {
                "pointer": "/data/attributes/password"
            },
            "status": "422",
            "title": "Unprocessable Entity"
        }
    ],
```

**Comment by lindyhopchris** [comment]
Good point. I need to throw specific exceptions that extend from `JsonApiException`, so that they can be ignored by the log. Or provide something that can be added to the exception handler via its `reportable()` method (much like the `renderable() method`).

**Comment by lindyhopchris** [comment]
The validation errors are already being thrown as a `JsonApiException`. The other exception thrown by the implementation that will also be reported is the `UnexpectedDocumentException` from the `spec` package.

At the moment without any mention of exception reporting in the docs, both (on a default Laravel setup) will get logged by the exception handler.

There's two things that need to happen here:

### Remove `UnexpectedDocumentException`

Ideally the `UnexpectedDocumentException` should be removed and replaced with throwing a `JsonApiException` from the spec package. That then unifies things so there is only one exception class to worry about from a reporting perspective.

These are translated in the `exceptions` package, but that doesn't really make sense when the `spec` package has its own translation files. Therefore we should move the translation of these errors into the `spec` files and just create `JsonApiException` classes instead.

### Add documentation on reporting `JsonApiException` classes.

The documentations to cover reporting `JsonApiException` instances. Typically you probably don't want them reported unless they are `5xx` errors: but some applications may actually want to log all. An example might be logging `4xx` errors as debug information, while `5xx` get logged by the default Laravel implementation, i.e. as errors.

We need to:

- [ ] Add a sensible default to the *Installation* chapter
- [ ] In the *Errors* chapter rename the *Error Handling* section to *Error Rendering*
- [ ] Add a new section to that chapter called *Error Reporting* with some examples of what to do.
- [ ] Add some helper methods to the `JsonApiException` class, e.g. `is5xx()`, `is4xx()` etc and make sure these are documented.

**Comment by lindyhopchris** [comment]
The next version of the docs will cover this. As the decision on logging is down to the implementing application, your options are as follows... just noting that the `is4xx()` and `is5xx()` methods will be tagged in the next release.

### 1. Ignore all JSON:API exceptions

```php
use LaravelJsonApi\Core\Exceptions\JsonApiException;

class Handler extends ExceptionHandler
{
    // ...

    /**
     * A list of the exception types that should not be reported.
     *
     * @var array
     */
    protected $dontReport = [
        JsonApiException::class,
    ];

    // ...
}
```

### Only log 5xx errors

```php
use LaravelJsonApi\Core\Exceptions\JsonApiException;

/**
 * Register the exception handling callbacks for the application.
 *
 * @return void
 */
public function register()
{
    $this->reportable(function (JsonApiException $ex) {
        if (!$ex->is5xx()) {
          return false;
        }
    });

    // ...
}
```

### Log 4xx errors as debug info and let 5xx errors get reported

```php
$this->reportable(function (JsonApiException $ex) {
    if ($ex->is4xx()) {
      logger('JSON:API client exception.', $ex->getErrors()->toArray());
      return false;
    }
});
```
