### ISSUE TITLE
Pass Router instance through to the Closure 

### ISSUE THREAD

**Issue by plunkettscott** [laravel-json-api/laravel#9]
This might be a bit unorthodox, but I think it would be beneficial to provide the passed Router object for registering actions alongside the resource routes.

Here's an example of how this could look:

```php
JsonApiRoute::server('v1')
    ->prefix('v1')
    ->resources(function ($server, $routes) {
        // /v1/server/...
        $server->resource('servers', ServersController::class);
        $routes->post('servers/{server}/shutdown', [ServersController::class, 'performShutdown']);
    })
```

Implementation would be as simple as accepting a `$routes` variable (the Router instance for the group) [as the only parameter to the group callback](https://github.com/laravel-json-api/laravel/blob/c9a78c8b7442a36af4b30079bd2c20aed815b246/src/Routing/PendingServerRegistration.php#L144) and passing that `$routes` variable [as the second parameter to the resources Closure](https://github.com/laravel-json-api/laravel/blob/c9a78c8b7442a36af4b30079bd2c20aed815b246/src/Routing/PendingServerRegistration.php#L148).

**Comment by lindyhopchris** [comment]
I think you can just pass `$this->router` through as the second argument:
https://github.com/laravel-json-api/laravel/blob/c9a78c8b7442a36af4b30079bd2c20aed815b246/src/Routing/PendingServerRegistration.php#L32

Would be happy with that. Any chance you can do a PR?

**Comment by plunkettscott** [comment]
Absolutely!
