### ISSUE TITLE
missing middleware when register custom action

### ISSUE THREAD

**Issue by eduardduta** [laravel-json-api/laravel#90]
My middleware is present on all default  methods for resource but it's missing when i declare custom action. 

Ex: 
```
Route::name('api.')->middleware(TenantIdentifier::class)->group(function (Router $router) {
    JsonApiRoute::server('api')
        ->resources(function (ResourceRegistrar $server) {
            $server
                ->resource('resource name', PatientController::class)
                ->actions(function (ActionRegistrar $actions) {
                    $actions
                        ->withId()
                        ->get("image", 'image');
                })->middleware(TenantIdentifier::class);
        });
});
```

**Comment by lindyhopchris** [comment]
Thanks for opening here, and reporting this issue. Most likely a bug as I probably haven't written a test for this scenario.

**Comment by lindyhopchris** [comment]
@eduardduta I've added a test for this scenario and it's passing - I cannot therefore reproduce the bug. You can see the test in the commit linked above.

Your example is a bit strange because it's registering the same middleware (`TenantIdentifier`) twice. However, as you'll see from the test if both those middleware methods are called, then the route has the correct middleware list on it.

There's not much else I can do at this point without you providing more information. For example, are you able to copy and paste the output of `route:list` (obviously only paste the routes that are to do with this resource). I need you to confirm for sure that the middleware column in that output definitely doesn't have the list that you're expecting.

**Comment by eduardduta** [comment]
It's strange, now i can see it indeed. Second call for middleware was when i tried if to apply that middleware and at that point was unsuccessful. I remove my changes and it seems to work and i can't even reproduce that bug  

Thank you for support !

Now is present in route:list 
3:121:| localhost      | GET|HEAD | api/patient/{patient}/media                   | api.patient.media            | App\Http\Controllers\Api\PatientController@showRelated            | App\Http\Middleware\TenantIdentifier                      |
4:123:| localhost      | POST     | api/patient/{patient}/media                   |api.patient.upload           | App\Http\Controllers\Api\PatientController@upload                 | App\Http\Middleware\TenantIdentifier                      |
11:161:| localhost      | GET|HEAD | api/patient/{patient}/relationships/media     |api.patient.media.show       | App\Http\Controllers\Api\PatientController@showRelationship       | App\Http\Middleware\TenantIdentifier                      |
12:163:| localhost      | PATCH    | api/patient/{patient}/relationships/media     |api.patient.media.update     | App\Http\Controllers\Api\PatientController@updateRelationship     | App\Http\Middleware\TenantIdentifier                      |
13:165:| localhost      | POST     | api/patient/{patient}/relationships/media     |api.patient.media.attach     | App\Http\Controllers\Api\PatientController@attachRelationship     | App\Http\Middleware\TenantIdentifier                      |
14:167:| localhost      | DELETE   | api/patient/{patient}/relationships/media     |api.patient.media.detach     | App\Http\Controllers\Api\PatientController@detachRelationship     | App\Http\Middleware\TenantIdentifier                      |

**Comment by lindyhopchris** [comment]
No problem, glad it's working now!

(PS if you cache your routes in development, then clearing the cache would have solved the issue. Personally I don't cache routes in development. Just mentioning this now in case it was the source of the problem!)
