### ISSUE TITLE
include fields from hasMany relations

### ISSUE THREAD

**Issue by onward-web** [laravel-json-api/laravel#94]
Hello. Please tell me how I can include fields with one-to-many relationships in the output. 

For example I have "PostSchema" 

```
class PostSchemaextends Schema{

public function fields(): array
    {
        return [
            ID::make(),
            Str::make('title'),
            Str::make('description'),            
            Map::make('comments', [              
                Str::make('author'),
		Str::make('text'),
            ])->on('comments'),

        ];
    }
 protected array $with = ['comnents'];
}

```

```
class Post extends Model
{

    protected $guarded = [];

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}
```

That is, the task is to derive certain fields from a one-to-many relationship into the results of the issue. 
I have error "LogicException Unable to encode compound document."

**Comment by lindyhopchris** [comment]
I'm sorry but I don't really understand your question.

In relation to the exception "Unable to encode compound document." This exception will always have a **previous exception**, which will explain why the document cannot be encoded. Please can you provide details of the previous exception?

**Comment by onward-web** [comment]
I would like to select Post and field from relation "Comments" in result for

GET http://example.com/api/v1/posts

Not sure if this works "Map" for one-to-many relationships:
```
Map::make('comments', [              
                Str::make('author'),
		Str::make('text'),
            ])->on('comments'),
```

If I remove the Map in fields method, the error disappears" Unable to encode compound document." 
That is, the Map method cannot select fields from a one-to-many relationship, or I am doing something wrong. 



For example, I would like to get the fields "author" and "text" from the relationship one to many "comments" as an array of data (the document is generated manually) 

```
Array
(
	..
    [data] => Array
        (
            [0] => Array
                (
                    [type] => post
                    [id] => 1
                    [attributes] => Array
                        (
                            [title] => My post
                            [description] => Text my post
                            [comments] => Array
				  [0] => (
                                    [author] =>  'Test'
				    [text] =>  'Good post'
                                  ),
				[1] => (
                                    [author] =>  'Test2'
				     [text] =>  'Good post2'
                                ),

                        )

                   ...
	          )
	)
)

```

**Comment by lindyhopchris** [comment]
The `Map` field is for an attribute. You're trying to add a relationship. For that, read the docs here:
https://laraveljsonapi.io/docs/1.0/schemas/relationships.html

**Comment by lindyhopchris** [comment]
Closing this as I believe the question has been answered. You need to use a relationship field for a relationship, not an attribute field.
