### ISSUE TITLE
POST with empty body cause error

### ISSUE THREAD

**Issue by bbprojectnet** [laravel-json-api/laravel#97]
When i try create new resource but with empty body request i get that response:

```
	"errors": [
		{
			"status": "500",
			"title": "Internal Server Error"
		}
	],
```
```
local.ERROR: Expecting an array resource with a type field. {"userId":12,"exception":"[object] (InvalidArgumentException(code: 0): Expecting an array resource with a type field. at [...]\\vendor\\laravel-json-api\\core\\src\\Core\\Document\\ResourceObject.php:132)"} 
```

Shouldn't I get a message from the document validator in this situation?

**Comment by lindyhopchris** [comment]
Yes you should. Not sure about this - will have to investigate.

**Comment by lindyhopchris** [comment]
I can't reproduce this - the code definitely does throw a correct error for an empty request. I get:

```http
HTTP/1.1 400 Bad Request
Server: nginx/1.18.0 (Ubuntu)
Content-Type: application/vnd.api+json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache, private
Date: Sat, 03 Jul 2021 10:27:14 GMT
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
Access-Control-Allow-Origin: *

{
  "jsonapi": {
    "version": "1.0"
  },
  "errors": [
    {
      "detail": "Expecting JSON to decode.",
      "status": "400",
      "title": "Invalid JSON"
    }
  ]
}
```

To progress this, I'll need to the full stack trace of your error. Nothing creates the `ResourceObject` class until after the body has been parsed against the JSON:API spec - so I need to see your stack trace to understand what's going on.

**Comment by bbprojectnet** [comment]
I found whrere is the problem. When you try to declare `prepareForValidation` in your Request class (which is child class of Laravel FormRequest) it happends. Problably because Laravel JSON API also override that method - it's unexpected behavior from the viewpoint of end dev, because that method should be possible to whithout siede effects.
